/**
 * @file tests/e2e/routes/system/permission-enforcement.spec.ts
 * @description E2E tests verifying that removing a permission actually blocks
 *   the corresponding action at both the API and UI level.
 *
 * Tests the full pipeline: DB → role → user → hasPermissionWithRoles →
 * API guard → UI guard. Closes the gap where only role-level page access
 * was tested but granular permission removal was not.
 */

import { expect, test } from "@playwright/test";
import { loginAsAdmin, loginAs, ADMIN_CREDENTIALS } from "../../helpers/auth";
import { TEST_API_HEADERS } from "../../helpers/test-api";

const TEST_ROLE_ID = "e2e-perm-test-role";
const TEST_USER = {
  email: "perm-test@example.com",
  password: "PermissionTest123!",
  username: "PermTester",
};

/**
 * Create or update a role with specific permissions via the testing API.
 */
async function upsertTestRole(page: any, permissions: string[]) {
  const res = await page.request.post("/api/testing", {
    headers: TEST_API_HEADERS,
    data: {
      action: "insert",
      collectionId: "roles",
      data: {
        _id: TEST_ROLE_ID,
        name: "E2E Permission Test Role",
        description: "Auto-generated by permission-enforcement E2E test",
        permissions,
        isAdmin: false,
      },
    },
  });

  // If insert fails because it already exists, update it
  if (!res.ok()) {
    const updateRes = await page.request.post("/api/testing", {
      headers: TEST_API_HEADERS,
      data: {
        action: "update",
        collectionId: "roles",
        id: TEST_ROLE_ID,
        data: { permissions, isAdmin: false },
      },
    });
    if (!updateRes.ok()) {
      throw new Error(`Failed to upsert test role: ${await updateRes.text()}`);
    }
  }
}

/**
 * Create or update the test user with the test role.
 */
async function ensureTestUser(page: any) {
  const res = await page.request.post("/api/testing", {
    headers: TEST_API_HEADERS,
    data: {
      action: "prepare-test-user",
      email: TEST_USER.email,
      password: TEST_USER.password,
      role: TEST_ROLE_ID,
      username: TEST_USER.username,
    },
  });
  if (!res.ok()) {
    throw new Error(`Failed to create test user: ${await res.text()}`);
  }
  return (await res.json()).user;
}

test.describe("Permission Enforcement — Remove & Verify Block", () => {
  test.setTimeout(60_000);

  test.beforeAll(async ({ browser }) => {
    const ctx = await browser.newContext();
    const page = await ctx.newPage();

    // Login as admin to set up roles and users
    await loginAsAdmin(page);

    // Create role with full write + read permissions
    await upsertTestRole(page, [
      "collection:read",
      "collection:write",
      "collection:create",
      "media:read",
      "media:write",
    ]);
    // Create test user
    await ensureTestUser(page);

    await ctx.close();
  });

  test("Removing collection:write blocks entry creation via API (403)", async ({ page }) => {
    // --- Phase 1: User CAN create with write permission ---
    await loginAsAdmin(page);
    await upsertTestRole(page, [
      "collection:read",
      "collection:write",
      "collection:create",
      "media:read",
      "media:write",
    ]);
    await ensureTestUser(page);

    // Log in as the test user
    await loginAs(page, TEST_USER.email, TEST_USER.password);

    // Verify create works via API
    const createRes = await page.evaluate(async () => {
      const res = await fetch("/api/collections/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Permission Test Entry", status: "draft" }),
      });
      return { status: res.status, ok: res.ok };
    });
    expect(createRes.ok || createRes.status === 201).toBeTruthy();

    // --- Phase 2: Remove write permission ---
    await loginAs(page, ADMIN_CREDENTIALS.email, ADMIN_CREDENTIALS.password); // back to admin
    await upsertTestRole(page, ["collection:read", "media:read"]); // write removed

    // --- Phase 3: User is now BLOCKED ---
    await loginAs(page, TEST_USER.email, TEST_USER.password);

    const blockedRes = await page.evaluate(async () => {
      const res = await fetch("/api/collections/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Should Be Blocked", status: "draft" }),
      });
      try {
        const body = await res.json();
        return { status: res.status, ok: res.ok, body };
      } catch {
        return { status: res.status, ok: res.ok };
      }
    });

    // Must be denied — 401, 403, or success:false
    const isDenied =
      !blockedRes.ok ||
      [401, 403].includes(blockedRes.status) ||
      blockedRes.body?.success === false;
    expect(isDenied).toBeTruthy();
  });

  test("Removing media:write blocks media upload via API (403)", async ({ page }) => {
    await loginAsAdmin(page);
    await upsertTestRole(page, ["collection:read", "media:read", "media:write"]);
    await ensureTestUser(page);

    // Verify media upload works
    await loginAs(page, TEST_USER.email, TEST_USER.password);
    const canUpload = await page.evaluate(async () => {
      const res = await fetch("/api/media/upload", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ test: "probe" }),
      });
      // We expect a specific error about the file, NOT a 403/401
      return res.status !== 401 && res.status !== 403;
    });
    expect(canUpload).toBeTruthy();

    // Remove media:write
    await loginAs(page, ADMIN_CREDENTIALS.email, ADMIN_CREDENTIALS.password);
    await upsertTestRole(page, ["collection:read", "media:read"]); // write removed

    // Verify blocked
    await loginAs(page, TEST_USER.email, TEST_USER.password);
    const blockedUpload = await page.evaluate(async () => {
      const res = await fetch("/api/media/upload", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ test: "probe" }),
      });
      return { status: res.status };
    });

    expect([401, 403]).toContain(blockedUpload.status);
  });

  test("Permission removal survives page refresh (persisted to DB)", async ({ page }) => {
    await loginAsAdmin(page);
    await upsertTestRole(page, ["collection:read", "collection:write"]);
    await ensureTestUser(page);
    let probeResult: boolean | number;

    // Verify access works
    await loginAs(page, TEST_USER.email, TEST_USER.password);
    probeResult = await page.evaluate(async () => {
      const res = await fetch("/api/collections/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Pre-refresh", status: "draft" }),
      });
      return res.ok || res.status === 201;
    });
    expect(probeResult).toBeTruthy();

    // Remove permission as admin
    await loginAs(page, ADMIN_CREDENTIALS.email, ADMIN_CREDENTIALS.password);
    await upsertTestRole(page, ["collection:read"]); // write removed

    // Refresh and re-login as test user
    await page.goto("/login", { waitUntil: "domcontentloaded" });
    await loginAs(page, TEST_USER.email, TEST_USER.password);

    // Verify blocked after refresh
    probeResult = await page.evaluate(async () => {
      const res = await fetch("/api/collections/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Post-refresh", status: "draft" }),
      });
      return res.status;
    });
    expect([401, 403]).toContain(probeResult);
  });

  test("Permission gating blocks UI navigation to restricted pages", async ({ page }) => {
    await loginAsAdmin(page);
    await upsertTestRole(page, ["collection:read"]); // minimal permissions
    await ensureTestUser(page);

    await loginAs(page, TEST_USER.email, TEST_USER.password);

    // Try to access a restricted page
    await page.goto("/config/access-management", { waitUntil: "domcontentloaded" });

    // Should see access denied (403/401 page or forbidden text)
    const isDenied = await Promise.race([
      page
        .getByText(/forbidden|unauthorized|access denied|insufficient permissions/i)
        .first()
        .isVisible({ timeout: 10_000 })
        .catch(() => false),
      page
        .getByRole("heading", { name: /401|403/ })
        .first()
        .isVisible({ timeout: 10_000 })
        .catch(() => false),
    ]);
    expect(isDenied).toBeTruthy();
  });
});
