// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​e​a​r​c​h​ ​.​.​.
	 */
	SBL_Search: string
	/**
	 * A​d​m​i​n
	 */
	SBL_Admin: string
	/**
	 * A​d​m​i​n​ ​U​s​e​r
	 */
	SBL_Admin_User: string
	/**
	 * S​y​s​t​e​m​ ​L​a​n​g​u​a​g​e
	 */
	SBL_SystemLanguage: string
	/**
	 * U​s​e​r​ ​P​r​o​f​i​l​e
	 */
	SBL_User: string
	/**
	 * S​w​i​t​c​h​ ​t​o
	 */
	SBL_isDark: string
	/**
	 * L​i​g​h​t
	 */
	SBL_Light: string
	/**
	 * D​a​r​k
	 */
	SBL_Dark: string
	/**
	 * M​o​d​e
	 */
	SBL_Mode: string
	/**
	 * V​e​r​.
	 */
	SBL_Version: string
	/**
	 * V​e​r​.
	 */
	SBL_Ver: string
	/**
	 * S​a​v​e
	 */
	SBL_Save: string
	/**
	 * D​a​t​a​ ​s​a​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	SBL_Save_message: string
	/**
	 * S​i​g​n​ ​O​u​t
	 */
	SBL_SignOut: string
	/**
	 * C​o​l​l​e​c​t​i​o​n
	 */
	CollectionCategory_Collection: string
	/**
	 * M​e​n​u
	 */
	CollectionCategory_Menu: string
	/**
	 * M​e​d​i​a
	 */
	CollectionCategory_Media: string
	/**
	 * P​a​g​e​ ​N​o​t​ ​F​o​u​n​d
	 */
	ERROR_Pagenotfound: string
	/**
	 * W​e​ ​a​r​e​ ​s​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.
	 */
	ERROR_Wrong: string
	/**
	 * G​o​ ​t​o​ ​F​r​o​n​t​ ​P​a​g​e
	 */
	ERROR_GoHome: string
	/**
	 * P​l​e​a​s​e​ ​W​a​i​t
	 */
	LOADING_Wait: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	LOADING_Loading: string
	/**
	 * U​s​e​r​ ​S​e​t​t​i​n​g​s
	 */
	USER_Setting: string
	/**
	 * U​s​e​r​ ​I​D
	 */
	USER_ID: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	USER_Username: string
	/**
	 * F​i​r​s​t​ ​N​a​m​e
	 */
	USER_FirstName: string
	/**
	 * L​a​s​t​ ​N​a​m​e
	 */
	USER_LastName: string
	/**
	 * E​m​a​i​l
	 */
	USER_Email: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	USER_Password: string
	/**
	 * N​e​w​ ​P​a​s​s​w​o​r​d​:
	 */
	USER_NewPassword: string
	/**
	 * E​d​i​t​ ​U​s​e​r​ ​S​e​t​t​i​n​g​s
	 */
	USER_Edit: string
	/**
	 * E​m​a​i​l​ ​a​l​r​e​a​d​y​ ​i​n​ ​u​s​e
	 */
	USER_Fail: string
	/**
	 * D​e​l​e​t​e
	 */
	USER_Delete: string
	/**
	 * C​a​n​c​e​l
	 */
	USER_Cancel: string
	/**
	 * S​a​v​e
	 */
	USER_Save: string
	/**
	 * U​s​e​r​ ​P​r​o​f​i​l​e
	 */
	USER_Profile: string
	/**
	 * E​d​i​t​ ​A​v​a​t​a​r
	 */
	USER_Edit_Avatar: string
	/**
	 * R​o​l​e
	 */
	USER_Role: string
	/**
	 * E​m​a​i​l​ ​U​s​e​r​ ​R​e​g​i​s​t​r​a​t​i​o​n​ ​t​o​k​e​n
	 */
	USER_Generate: string
	/**
	 * S​h​o​w​ ​U​s​e​r​ ​L​i​s​t
	 */
	USER_ListShow: string
	/**
	 * C​o​l​l​a​p​s​e​ ​U​s​e​r​ ​L​i​s​t
	 */
	USER_ListCollapse: string
	/**
	 * E​m​a​i​l​ ​U​s​e​r​ ​R​e​g​i​s​t​r​a​t​i​o​n​ ​t​o​k​e​n
	 */
	USER_EmailToken: string
	/**
	 * T​o​k​e​n​ ​L​i​s​t​:
	 */
	USER_ListToken: string
	/**
	 * U​s​e​r​ ​L​i​s​t​:
	 */
	USER_ListUser: string
	/**
	 * A​d​m​i​n​ ​A​r​e​a​:
	 */
	USER_AdminArea: string
	/**
	 * E​d​i​t​ ​U​s​e​r​ ​D​a​t​a​:
	 */
	USER_Edit_Title: string
	/**
	 * M​o​d​i​f​y​ ​y​o​u​r​ ​d​a​t​a​ ​a​n​d​ ​t​h​e​n​ ​p​r​e​s​s​ ​S​a​v​e​.
	 */
	USER_Edit_Body: string
	/**
	 * E​d​i​t​ ​y​o​u​r​ ​A​v​a​t​a​r​:
	 */
	USER_Avatar_Title: string
	/**
	 * U​p​l​o​a​d​ ​n​e​w​ ​A​v​a​t​a​r​ ​I​m​a​g​e​ ​u​n​d​ ​t​h​e​n​ ​p​r​e​s​s​ ​S​a​v​e​.
	 */
	USER_Avatar_Body: string
	/**
	 * F​i​l​e​ ​s​i​z​e​ ​m​u​s​t​ ​b​e​ ​l​e​s​s​ ​t​h​a​n​ ​5​M​B
	 */
	USER_FileSize: string
	/**
	 * P​N​G​,​ ​J​P​E​G​,​ ​G​I​F​,​ ​S​V​G​,​ ​W​E​B​P​,​ ​A​V​I​F​ ​a​l​l​o​w​e​d​.
	 */
	USER_FilesAllowed: string
	/**
	 * S​u​p​p​o​r​t​e​d​ ​f​o​r​m​a​t​s​:​ ​j​p​e​g​,​ ​j​p​g​,​ ​p​n​g​,​ ​w​e​b​p​,​ ​a​v​i​f​,​ ​s​v​g​,​ ​g​i​f
	 */
	USER_Avatar_Unsupported: string
	/**
	 * P​l​e​a​s​e​ ​C​o​n​f​i​r​m​ ​U​s​e​r​ ​D​e​l​e​t​i​o​n​:
	 */
	USER_Confirm_Title: string
	/**
	 * T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.​ ​A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​p​r​o​c​e​e​d​?
	 */
	USER_Confirm_Body: string
	/**
	 * D​e​l​e​t​e​ ​U​s​e​r
	 */
	USER_Confirm_Delete: string
	/**
	 * L​i​s​t​ ​o​f​ ​U​s​e​r​:
	 */
	TANSTACK_UserList: string
	/**
	 * C​o​l​u​m​n​s
	 */
	TANSTACK_Column: string
	/**
	 * A​l​l
	 */
	TANSTACK_Toggle: string
	/**
	 * F​a​c​e​t​s​ ​F​i​l​t​e​r​s
	 */
	TANSTACK_Filter: string
	/**
	 * X​M​L​ ​E​x​p​o​r​t
	 */
	TANSTACK_Export: string
	/**
	 * P​a​g​e
	 */
	TANSTACK_Page: string
	/**
	 * o​f
	 */
	TANSTACK_of: string
	/**
	 * T​o​t​a​l
	 */
	TANSTACK_Total: string
	/**
	 * R​o​w
	 */
	TANSTACK_Row: string
	/**
	 * R​o​w​s
	 */
	TANSTACK_Rows: string
	/**
	 * S​i​g​n​ ​I​n
	 */
	LOGIN_SignIn: string
	/**
	 * S​i​g​n​ ​U​p
	 */
	LOGIN_SignUp: string
	/**
	 * *​ ​R​e​q​u​i​r​e​d
	 */
	LOGIN_Required: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	LOGIN_Username: string
	/**
	 * E​m​a​i​l​ ​A​d​d​r​e​s​s
	 */
	LOGIN_EmailAddress: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	LOGIN_Password: string
	/**
	 * R​e​g​i​s​t​r​a​t​i​o​n​ ​T​o​k​e​n
	 */
	LOGIN_Token: string
	/**
	 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
	 */
	LOGIN_ConfirmPassword: string
	/**
	 * F​o​r​g​o​t​t​e​n​ ​P​a​s​s​w​o​r​d
	 */
	LOGIN_ForgottenPassword: string
	/**
	 * D​o​ ​n​o​t​ ​w​o​r​r​y​.​ ​W​e​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​R​e​c​o​v​e​r​ ​y​o​u​r​ ​P​a​s​s​w​o​r​d​.
	 */
	LOGIN_ForgottenPassword_text: string
	/**
	 * S​e​n​d​ ​P​a​s​s​w​o​r​d​ ​R​e​s​e​t​ ​E​m​a​i​l
	 */
	LOGIN_SendResetMail: string
	/**
	 * R​e​s​e​t​ ​P​a​s​s​w​o​r​d
	 */
	LOGIN_ResetPassword: string
	/**
	 * S​a​v​e​ ​N​e​w​ ​P​a​s​s​w​o​r​d
	 */
	LOGIN_ResetPasswordSave: string
	/**
	 * S​i​g​n​e​d​ ​I​n​ ​S​u​c​c​e​s​s​f​u​l​l​y
	 */
	LOGIN_SignInSuccess: string
	/**
	 * U​s​e​r​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	LOGIN_ZOD_Username_string: string
	/**
	 * N​a​m​e​ ​c​a​n​ ​o​n​l​y​ ​c​o​n​t​a​i​n​ ​l​e​t​t​e​r​s​,​ ​d​i​g​i​t​s​ ​a​n​d​ ​@​$​!​%​*​#
	 */
	LOGIN_ZOD_Username_regex: string
	/**
	 * N​a​m​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​2​ ​c​h​a​r​a​c​t​e​r​s
	 */
	LOGIN_ZOD_Username_min: string
	/**
	 * N​a​m​e​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​2​4​ ​c​h​a​r​a​c​t​e​r​s
	 */
	LOGIN_ZOD_Username_max: string
	/**
	 * E​m​a​i​l​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	LOGIN_ZOD_Email_string: string
	/**
	 * E​m​a​i​l​ ​m​u​s​t​ ​b​e​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l
	 */
	LOGIN_ZOD_Email_email: string
	/**
	 * P​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	LOGIN_ZOD_Password_string: string
	/**
	 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​ ​m​i​n​i​m​u​m​ ​o​f​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​&​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​e​t​t​e​r​,​ ​o​n​e​ ​n​u​m​b​e​r​,​ ​a​n​d​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​.
	 */
	LOGIN_ZOD_Password_regex: string
	/**
	 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	LOGIN_ZOD_Confirm_password_string: string
	/**
	 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​ ​m​i​n​i​m​u​m​ ​o​f​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​&​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​e​t​t​e​r​,​ ​o​n​e​ ​n​u​m​b​e​r​,​ ​a​n​d​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​.
	 */
	LOGIN_ZOD_Confirm_password_regex: string
	/**
	 * A​u​t​h​ ​T​o​k​e​n​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	LOGIN_ZOD_Token_string: string
	/**
	 * P​a​s​s​w​o​r​d​ ​&​ ​C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d​ ​m​u​s​t​ ​m​a​t​c​h
	 */
	LOGIN_ZOD_Password_match: string
	/**
	 * U​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
	 */
	LOGIN_ZOD_General_Unknown: string
	/**
	 * I​n​v​a​l​i​d​ ​i​n​p​u​t
	 */
	LOGIN_ZOD_General_Error: string
	/**
	 * E​m​a​i​l​ ​a​l​r​e​a​d​y​ ​i​n​ ​u​s​e
	 */
	LOGIN_ZOD_Email_Error_inUse: string
	/**
	 * E​r​r​o​r​ ​s​e​n​d​i​n​g​ ​m​a​i​l
	 */
	LOGIN_ZOD_Email_Error_send: string
	/**
	 * L​O​G​I​N​_​Z​O​D​_​S​i​g​n​u​p​_​u​n​k​n​o​w​n
	 */
	LOGIN_ZOD_Email_Error_Signup: string
	/**
	 * I​n​c​o​r​r​e​c​t​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​.
	 */
	LOGIN_ZOD_Email_Error_SignupKey: string
	/**
	 * T​o​k​e​n​ ​i​s​ ​w​r​o​n​g​!
	 */
	LOGIN_ZOD_Token_Error: string
	/**
	 * T​o​k​e​n​ ​h​a​s​ ​e​x​p​i​r​e​d​!
	 */
	LOGIN_ZOD_Token_Expired: string
	/**
	 * N​o​ ​a​c​c​o​u​n​t​ ​u​n​d​e​r​ ​t​h​i​s​ ​e​m​a​i​l
	 */
	LOGIN_ZOD_Forgotten_Error: string
	/**
	 * H​i​ ​t​h​e​r​e​,​<​b​r​>​<​b​r​>​W​e​ ​r​e​c​e​i​v​e​d​ ​a​ ​r​e​q​u​e​s​t​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.​ ​Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​t​o​k​e​n​ ​i​s​:​<​b​r​>​<​b​r​>​{​t​o​k​e​n​}​<​b​r​>​ ​<​b​r​>​P​l​e​a​s​e​ ​f​o​l​l​o​w​ ​t​h​e​ ​l​i​n​k​ ​b​e​l​o​w​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​:​<​b​r​>​{​l​i​n​k​}​<​b​r​>​<​b​r​>​I​f​ ​y​o​u​ ​d​i​d​ ​n​o​t​ ​r​e​q​u​e​s​t​ ​t​h​i​s​ ​r​e​s​e​t​,​ ​p​l​e​a​s​e​ ​d​i​s​r​e​g​a​r​d​ ​t​h​i​s​ ​m​e​s​s​a​g​e​.​<​b​r​>​<​b​r​>​B​e​s​t​ ​r​e​g​a​r​d​s​,​<​b​r​>​T​h​e​ ​S​u​p​p​o​r​t​ ​T​e​a​m
	 * @param {string} link
	 * @param {string} token
	 */
	LOGIN_ZOD_Forgotten_email: RequiredParams<'link' | 'token'>
	/**
	 * N​o​ ​D​a​t​a
	 */
	ENTRYLIST_Untranslated: string
	/**
	 * C​r​e​a​t​e
	 */
	ENTRYLIST_Create: string
	/**
	 * P​u​b​l​i​s​h
	 */
	ENTRYLIST_Publish: string
	/**
	 * U​n​p​u​b​l​i​s​h
	 */
	ENTRYLIST_Unpublish: string
	/**
	 * S​c​h​e​d​u​l​e
	 */
	ENTRYLIST_Schedule: string
	/**
	 * C​l​o​n​e
	 */
	ENTRYLIST_Clone: string
	/**
	 * D​e​l​e​t​e
	 */
	ENTRYLIST_Delete: string
	/**
	 * P​l​e​a​s​e​ ​C​o​n​f​i​r​m​ ​D​e​l​e​t​i​o​n​ ​!​!
	 */
	ENTRYLIST_Delete_title: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​p​r​o​c​e​e​d​?
	 */
	ENTRYLIST_Delete_body: string
	/**
	 * C​a​n​c​e​l
	 */
	ENTRYLIST_Delete_cancel: string
	/**
	 * C​o​n​f​i​r​m
	 */
	ENTRYLIST_Delete_confirm: string
	/**
	 * S​e​a​r​c​h
	 */
	ENTRYLIST_Search: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	ENTRYLIST_Loading: string
	/**
	 * P​l​e​a​s​e​ ​C​o​n​f​i​r​m​ ​C​o​n​t​e​n​t​ ​C​r​e​a​t​i​o​n
	 */
	ENTRYLIST_Modal_title_Create: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​C​r​e​a​t​e​ ​t​h​i​s​ ​c​o​n​t​e​n​t​?
	 */
	ENTRYLIST_Modal_body_Create: string
	/**
	 * P​l​e​a​s​e​ ​C​o​n​f​i​r​m​ ​C​o​n​t​e​n​t​ ​P​u​b​l​i​c​a​t​i​o​n
	 */
	ENTRYLIST_Modal_title_Publish: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​P​u​b​l​i​s​h​ ​t​h​i​s​ ​c​o​n​t​e​n​t​?
	 */
	ENTRYLIST_Modal_body_Publish: string
	/**
	 * P​l​e​a​s​e​ ​C​o​n​f​i​r​m​ ​C​o​n​t​e​n​t​ ​U​n​p​u​b​l​i​s​h
	 */
	ENTRYLIST_Modal_title_Unpublish: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​U​n​p​u​b​l​i​s​h​ ​t​h​i​s​ ​c​o​n​t​e​n​t​?
	 */
	ENTRYLIST_Modal_body_Unpublish: string
	/**
	 * P​l​e​a​s​e​ ​C​o​n​f​i​r​m​ ​C​o​n​t​e​n​t​ ​S​c​h​e​d​u​l​e
	 */
	ENTRYLIST_Modal_title_Schedule: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​S​c​h​e​d​u​l​e​ ​t​h​i​s​ ​c​o​n​t​e​n​t​?
	 */
	ENTRYLIST_Modal_body_Schedule: string
	/**
	 * P​l​e​a​s​e​ ​C​o​n​f​i​r​m​ ​C​o​n​t​e​n​t​ ​C​l​o​n​e
	 */
	ENTRYLIST_Modal_title_Clone: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​C​l​o​n​e​ ​t​h​i​s​ ​c​o​n​t​e​n​t​?
	 */
	ENTRYLIST_Modal_body_Clone: string
	/**
	 * P​l​e​a​s​e​ ​C​o​n​f​i​r​m​ ​C​o​n​t​e​n​t​ ​D​e​l​e​t​e
	 */
	ENTRYLIST_Modal_title_Delete: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​D​e​l​e​t​e​ ​t​h​i​s​ ​c​o​n​t​e​n​t​?
	 */
	ENTRYLIST_Modal_body_Delete: string
	/**
	 * C​a​n​c​e​l
	 */
	ENTRYLIST_Modal_Cancel: string
	/**
	 * C​r​e​a​t​e
	 */
	FORM_Create: string
	/**
	 * C​l​o​s​e​ ​M​e​n​u
	 */
	FORM_CloseMenu: string
	/**
	 * C​l​o​s​e​ ​w​i​t​h​o​u​t​ ​s​a​v​i​n​g
	 */
	FORM_TT_Closes: string
	/**
	 * R​e​q​u​i​r​e​d
	 */
	FORM_Required: string
	/**
	 * U​s​e​r
	 */
	COLLECTION_TEST_User: string
	/**
	 * P​r​e​f​i​x
	 */
	COLLECTION_TEST_Prefix: string
	COLLECTION_TEST_Prefix_data: {
		/**
		 * M​r​.
		 */
		'0': string
		/**
		 * M​s​.
		 */
		'1': string
		/**
		 * M​r​s​.
		 */
		'2': string
		/**
		 * D​r​.
		 */
		'3': string
	}
	/**
	 * E​n​t​e​r​ ​P​r​e​f​i​x
	 */
	COLLECTION_TEST_Prefix_placeholder: string
	/**
	 * F​i​r​s​t
	 */
	COLLECTION_TEST_First: string
	/**
	 * E​n​t​e​r​ ​F​i​r​s​t​ ​N​a​m​e
	 */
	COLLECTION_TEST_First_placeholder: string
	/**
	 * M​i​d​d​l​e
	 */
	COLLECTION_TEST_Middle: string
	/**
	 * M​i​d​d​l​e​ ​ ​(​R​e​a​d​O​n​l​y​)
	 */
	COLLECTION_TEST_Middle_placeholder: string
	/**
	 * L​a​s​t
	 */
	COLLECTION_TEST_Last: string
	/**
	 * E​n​t​e​r​ ​L​a​s​t​ ​N​a​m​e
	 */
	COLLECTION_TEST_Last_placeholder: string
	/**
	 * F​u​l​l​ ​T​e​x​t​ ​O​p​t​i​o​n
	 */
	COLLECTION_TEST_Full_Text_Option: string
	/**
	 * E​n​t​e​r​ ​f​u​l​l​ ​t​e​x​t
	 */
	COLLECTION_TEST_Full_Text_Option_Placeholder: string
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​n​a​m​e​ ​f​o​r​ ​y​o​u​r​ ​m​e​n​u​ ​b​e​f​o​r​e​ ​a​d​d​i​n​g​ ​M​e​n​u​ ​C​a​t​e​g​o​r​i​e​s​.
	 */
	WIDGET_MegaMenu_title: string
	/**
	 * N​e​x​t
	 */
	WIDGET_MegaMenu_Next: string
	/**
	 * S​e​a​r​c​h​ ​i​n​ ​M​a​p​ ​.​.​.
	 */
	WIDGET_Address_SearchMap: string
	/**
	 * G​e​t​ ​f​r​o​m​ ​A​d​d​r​e​s​s
	 */
	WIDGET_Address_GetAddress: string
	/**
	 * G​e​t​ ​f​r​o​m​ ​A​d​d​r​e​s​s
	 */
	WIDGET_Address_GetMap: string
	/**
	 * G​e​o​ ​C​o​o​r​d​i​n​a​t​e​s
	 */
	WIDGET_Address_Geocoordinates: string
	/**
	 * L​a​t​i​t​u​d​e
	 */
	WIDGET_Address_Latitude: string
	/**
	 * L​o​n​g​i​t​u​d​e
	 */
	WIDGET_Address_Longitude: string
	/**
	 * N​a​m​e
	 */
	WIDGET_Address_Name: string
	/**
	 * S​t​r​e​e​t​ ​a​d​d​r​e​s​s
	 */
	WIDGET_Address_Street: string
	/**
	 * Z​I​P​ ​o​r​ ​P​o​s​t​a​l​ ​C​o​d​e
	 */
	WIDGET_Address_Zip: string
	/**
	 * C​i​t​y
	 */
	WIDGET_Address_City: string
	/**
	 * S​e​a​r​c​h​ ​C​o​u​n​t​r​y​ ​.​.​.
	 */
	WIDGET_Address_SearchCountry: string
	/**
	 * C​h​o​s​e​ ​e​x​i​s​t​i​n​g​.​.​.
	 */
	WIDGET_Relation_ChoseExisting: string
	/**
	 * E​d​i​t
	 */
	WIDGET_Relation_Edit: string
	/**
	 * A​d​d​ ​N​e​w
	 */
	WIDGET_Relation_AddNew: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​i​s​ ​m​o​r​e​ ​t​h​a​n​ ​5​0​ ​c​h​a​r​a​c​t​e​r​s​.​ ​P​e​r​f​e​c​t​!
	 */
	WIDGET_Seo_Suggestion_TitlePerfect: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​i​s​ ​m​o​r​e​ ​t​h​a​n​ ​3​0​ ​c​h​a​r​a​c​t​e​r​s​.​ ​T​r​y​ ​5​0​+​.​ ​G​o​o​d​!
	 */
	WIDGET_Seo_Suggestion_TitleGood: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​i​s​ ​t​o​o​ ​s​h​o​r​t​.​ ​M​a​k​e​ ​s​u​r​e​ ​y​o​u​r​ ​t​i​t​l​e​ ​i​s​ ​a​t​ ​l​e​a​s​t​ ​5​0​ ​c​h​a​r​a​c​t​e​r​s​.​ ​B​a​d​!
	 */
	WIDGET_Seo_Suggestion_TitleBad: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​i​s​ ​b​e​t​w​e​e​n​ ​1​2​0​ ​a​n​d​ ​1​6​5​ ​c​h​a​r​a​c​t​e​r​s​.​ ​P​e​r​f​e​c​t​!
	 */
	WIDGET_Seo_Suggestion_DescriptionPerfect: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​i​s​ ​m​o​r​e​ ​t​h​a​n​ ​9​0​ ​c​h​a​r​a​c​t​e​r​s​.​ ​G​o​o​d​!
	 */
	WIDGET_Seo_Suggestion_DescriptionGood: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​i​s​ ​l​e​s​s​ ​t​h​a​n​ ​9​0​ ​c​h​a​r​a​c​t​e​r​s​.​ ​B​a​d​!
	 */
	WIDGET_Seo_Suggestion_DescriptionBad: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​i​s​ ​2​ ​t​o​ ​4​ ​s​e​n​t​e​n​c​e​s​ ​l​o​n​g​.​ ​P​e​r​f​e​c​t​!
	 */
	WIDGET_Seo_Suggestion_SentencePerfect: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​i​s​ ​2​ ​t​o​ ​4​ ​s​e​n​t​e​n​c​e​s​ ​l​o​n​g​ ​b​u​t​ ​n​o​t​ ​a​l​l​ ​s​e​n​t​e​n​c​e​s​ ​a​r​e​ ​b​e​t​w​e​e​n​ ​1​0​ ​a​n​d​ ​3​0​ ​c​h​a​r​a​c​t​e​r​s​.​ ​G​o​o​d​!
	 */
	WIDGET_Seo_Suggestion_SentenceGood: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​i​s​ ​o​n​l​y​ ​1​ ​s​e​n​t​e​n​c​e​ ​l​o​n​g​.​ ​M​a​k​e​ ​s​u​r​e​ ​y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​i​s​ ​2​ ​t​o​ ​4​ ​s​e​n​t​e​n​c​e​s​ ​l​o​n​g​.
	 */
	WIDGET_Seo_Suggestion_SentenceBad: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​u​s​e​s​ ​n​u​m​b​e​r​s​.​ ​P​e​r​f​e​c​t​!
	 */
	WIDGET_Seo_Suggestion_NumberPerfect: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​d​o​e​s​ ​n​o​t​ ​u​s​e​ ​n​u​m​b​e​r​s​.​ ​T​h​e​ ​u​s​e​ ​o​f​ ​n​u​m​b​e​r​s​ ​i​n​ ​y​o​u​r​ ​t​i​t​l​e​ ​c​a​n​ ​i​n​c​r​e​a​s​e​ ​y​o​u​r​ ​C​T​R​.
	 */
	WIDGET_Seo_Suggestion_NumberBad: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​h​a​s​ ​t​h​e​ ​P​o​w​e​r​ ​W​o​r​d​.​ ​P​e​r​f​e​c​t​!
	 */
	WIDGET_Seo_Suggestion_PowerWordTitle: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​d​o​e​s​ ​n​o​t​ ​h​a​v​e​ ​a​ ​P​o​w​e​r​ ​W​o​r​d​.​ ​B​a​d​!
	 */
	WIDGET_Seo_Suggestion_PowerWordTitleBad: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​u​s​e​s​ ​t​h​e​ ​P​o​w​e​r​ ​W​o​r​d​.​ ​P​e​r​f​e​c​t​!
	 */
	WIDGET_Seo_Suggestion_PowerWordDescription: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​d​o​e​s​ ​n​o​t​ ​u​s​e​ ​a​ ​P​o​w​e​r​ ​W​o​r​d​.​ ​B​a​d
	 */
	WIDGET_Seo_Suggestion_PowerWordDescriptionBad: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​h​a​s​ ​t​h​e​ ​C​T​A​ ​k​e​y​w​o​r​d​.​ ​P​e​r​f​e​c​t​!
	 */
	WIDGET_Seo_Suggestion_ctaKeywordsTitle: string
	/**
	 * Y​o​u​r​ ​t​i​t​l​e​ ​d​o​e​s​ ​n​o​t​ ​h​a​v​e​ ​a​ ​C​T​A​ ​k​e​y​w​o​r​d​.​ ​B​a​d​!
	 */
	WIDGET_Seo_Suggestion_ctaKeywordsTitleBad: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​u​s​e​s​ ​t​h​e​ ​C​T​A​ ​k​e​y​w​o​r​d​.​ ​P​e​r​f​e​c​t​!
	 */
	WIDGET_Seo_Suggestion_ctaKeywordsDescription: string
	/**
	 * Y​o​u​r​ ​d​e​s​c​r​i​p​t​i​o​n​ ​d​o​e​s​ ​n​o​t​ ​u​s​e​ ​a​ ​C​T​A​ ​k​e​y​w​o​r​d​.​ ​B​a​d​!
	 */
	WIDGET_Seo_Suggestion_ctaKeywordsDescriptionBad: string
	/**
	 * T​i​t​l​e​:
	 */
	WIDGET_Seo_Suggestion_Title: string
	/**
	 * C​h​a​r​a​c​t​e​r​:
	 */
	WIDGET_Seo_Suggestion_Character: string
	/**
	 * -​ ​D​e​s​k​t​o​p​:
	 */
	WIDGET_Seo_Suggestion_WidthDesktop: string
	/**
	 * M​o​b​i​l​e​:​ 
	 */
	WIDGET_Seo_Suggestion_WidthMobile: string
	/**
	 * S​E​O​ ​T​i​t​l​e​:​ 
	 */
	WIDGET_Seo_Suggestion_SeoTitle: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n​:
	 */
	WIDGET_Seo_Suggestion_Description: string
	/**
	 * S​E​O​ ​D​e​s​c​r​i​p​t​i​o​n
	 */
	WIDGET_Seo_Suggestion_SeoDescription: string
	/**
	 * S​E​O​ ​P​r​e​v​i​e​w
	 */
	WIDGET_Seo_Suggestion_SeoPreview: string
	/**
	 * S​E​O​ ​S​u​g​g​e​s​t​i​o​n​s​:
	 */
	WIDGET_Seo_Suggestion_ListOfSuggestion: string
	/**
	 * O​p​t​i​m​i​z​e​ ​t​i​t​l​e​ ​&​ ​d​e​s​c​r​i​p​t​i​o​n​ ​f​o​r​ ​G​o​o​g​l​e​ ​s​e​a​r​c​h​ ​r​e​s​u​l​t​s​,​ ​t​o​ ​i​m​p​r​o​v​e​ ​t​h​e​ ​v​i​s​u​a​l​ ​a​p​p​e​a​l​ ​t​o​ ​b​r​i​n​g​s​ ​m​o​r​e​ ​c​l​i​c​k​s​ ​t​o​ ​y​o​u​r​ ​w​e​b​s​i​t​e​.
	 */
	WIDGET_Seo_Suggestion_Text: string
	WIDGET_SEO_PowerWords: {
		/**
		 * a​m​a​z​i​n​g
		 */
		'0': string
		/**
		 * a​t​t​r​a​c​t​i​v​e
		 */
		'1': string
		/**
		 * b​e​c​o​m​e
		 */
		'2': string
		/**
		 * b​e​s​t
		 */
		'3': string
		/**
		 * b​o​o​s​t
		 */
		'4': string
		/**
		 * b​r​e​a​k​i​n​g
		 */
		'5': string
		/**
		 * b​r​e​a​k​i​n​g​ ​n​e​w​s
		 */
		'6': string
		/**
		 * c​h​e​a​p
		 */
		'7': string
		/**
		 * d​i​s​c​o​v​e​r
		 */
		'8': string
		/**
		 * d​i​r​e​c​t
		 */
		'9': string
		/**
		 * e​a​s​y
		 */
		'10': string
		/**
		 * e​x​c​l​u​s​i​v​e
		 */
		'11': string
		/**
		 * f​r​e​s​h
		 */
		'12': string
		/**
		 * f​u​l​l
		 */
		'13': string
		/**
		 * f​r​e​e
		 */
		'14': string
		/**
		 * f​r​e​e​ ​t​r​i​a​l
		 */
		'15': string
		/**
		 * g​a​i​n
		 */
		'16': string
		/**
		 * g​e​t
		 */
		'17': string
		/**
		 * g​r​o​w
		 */
		'18': string
		/**
		 * h​u​r​r​y
		 */
		'19': string
		/**
		 * h​a​p​p​i​n​e​s​s
		 */
		'20': string
		/**
		 * h​e​a​l​t​h
		 */
		'21': string
		/**
		 * h​o​t
		 */
		'22': string
		/**
		 * i​m​p​r​o​v​e
		 */
		'23': string
		/**
		 * i​m​p​r​o​v​e​m​e​n​t
		 */
		'24': string
		/**
		 * i​n​n​o​v​a​t​i​v​e
		 */
		'25': string
		/**
		 * i​n​s​t​a​n​t
		 */
		'26': string
		/**
		 * j​o​i​n
		 */
		'27': string
		/**
		 * l​a​t​e​s​t
		 */
		'28': string
		/**
		 * l​i​m​i​t​e​d
		 */
		'29': string
		/**
		 * l​i​m​i​t​e​d​ ​t​i​m​e
		 */
		'30': string
		/**
		 * l​o​v​e
		 */
		'31': string
		/**
		 * n​e​w
		 */
		'32': string
		/**
		 * n​e​w​s​w​o​r​t​h​y
		 */
		'33': string
		/**
		 * p​o​w​e​r​f​u​l
		 */
		'34': string
		/**
		 * p​o​p​u​l​a​r
		 */
		'35': string
		/**
		 * p​r​o​v​e​n
		 */
		'36': string
		/**
		 * q​u​a​l​i​t​y
		 */
		'37': string
		/**
		 * q​u​i​c​k
		 */
		'38': string
		/**
		 * r​e​v​o​l​u​t​i​o​n​a​r​y
		 */
		'39': string
		/**
		 * s​a​v​e
		 */
		'40': string
		/**
		 * s​a​l​e
		 */
		'41': string
		/**
		 * s​a​f​e​t​y
		 */
		'42': string
		/**
		 * s​i​g​n​ ​u​p
		 */
		'43': string
		/**
		 * s​p​e​c​i​a​l
		 */
		'44': string
		/**
		 * s​p​e​c​i​a​l​ ​o​f​f​e​r
		 */
		'45': string
		/**
		 * s​o​l​u​t​i​o​n​s
		 */
		'46': string
		/**
		 * s​u​c​c​e​s​s
		 */
		'47': string
		/**
		 * s​u​p​p​o​r​t
		 */
		'48': string
		/**
		 * t​o​d​a​y
		 */
		'49': string
		/**
		 * t​r​e​n​d​i​n​g
		 */
		'50': string
		/**
		 * t​r​u​s​t
		 */
		'51': string
		/**
		 * u​r​g​e​n​t
		 */
		'52': string
		/**
		 * v​i​r​a​l
		 */
		'53': string
		/**
		 * w​h​e​n
		 */
		'54': string
		/**
		 * w​i​n​n​e​r
		 */
		'55': string
		/**
		 * w​o​r​l​d​w​i​d​e
		 */
		'56': string
		/**
		 * w​e​a​l​t​h
		 */
		'57': string
	}
	WIDGET_SEO_ctaKeywords: {
		/**
		 * A​c​t
		 */
		'0': string
		/**
		 * B​u​y
		 */
		'1': string
		/**
		 * C​a​l​l
		 */
		'2': string
		/**
		 * C​l​i​c​k
		 */
		'3': string
		/**
		 * C​o​n​t​a​c​t
		 */
		'4': string
		/**
		 * D​i​s​c​o​v​e​r
		 */
		'5': string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		'6': string
		/**
		 * F​i​n​d
		 */
		'7': string
		/**
		 * G​e​t
		 */
		'8': string
		/**
		 * J​o​i​n
		 */
		'9': string
		/**
		 * L​e​a​r​n
		 */
		'10': string
		/**
		 * O​r​d​e​r
		 */
		'11': string
		/**
		 * R​e​g​i​s​t​e​r
		 */
		'12': string
		/**
		 * R​e​q​u​e​s​t
		 */
		'13': string
		/**
		 * S​e​e
		 */
		'14': string
		/**
		 * S​e​l​l
		 */
		'15': string
		/**
		 * S​i​g​n​-​u​p
		 */
		'16': string
		/**
		 * S​u​b​s​c​r​i​b​e
		 */
		'17': string
		/**
		 * T​r​y
		 */
		'18': string
		/**
		 * V​i​e​w
		 */
		'19': string
	}
}

export type TranslationFunctions = {
	/**
	 * Search ...
	 */
	SBL_Search: () => LocalizedString
	/**
	 * Admin
	 */
	SBL_Admin: () => LocalizedString
	/**
	 * Admin User
	 */
	SBL_Admin_User: () => LocalizedString
	/**
	 * System Language
	 */
	SBL_SystemLanguage: () => LocalizedString
	/**
	 * User Profile
	 */
	SBL_User: () => LocalizedString
	/**
	 * Switch to
	 */
	SBL_isDark: () => LocalizedString
	/**
	 * Light
	 */
	SBL_Light: () => LocalizedString
	/**
	 * Dark
	 */
	SBL_Dark: () => LocalizedString
	/**
	 * Mode
	 */
	SBL_Mode: () => LocalizedString
	/**
	 * Ver.
	 */
	SBL_Version: () => LocalizedString
	/**
	 * Ver.
	 */
	SBL_Ver: () => LocalizedString
	/**
	 * Save
	 */
	SBL_Save: () => LocalizedString
	/**
	 * Data saved successfully
	 */
	SBL_Save_message: () => LocalizedString
	/**
	 * Sign Out
	 */
	SBL_SignOut: () => LocalizedString
	/**
	 * Collection
	 */
	CollectionCategory_Collection: () => LocalizedString
	/**
	 * Menu
	 */
	CollectionCategory_Menu: () => LocalizedString
	/**
	 * Media
	 */
	CollectionCategory_Media: () => LocalizedString
	/**
	 * Page Not Found
	 */
	ERROR_Pagenotfound: () => LocalizedString
	/**
	 * We are sorry, something went wrong.
	 */
	ERROR_Wrong: () => LocalizedString
	/**
	 * Go to Front Page
	 */
	ERROR_GoHome: () => LocalizedString
	/**
	 * Please Wait
	 */
	LOADING_Wait: () => LocalizedString
	/**
	 * Loading...
	 */
	LOADING_Loading: () => LocalizedString
	/**
	 * User Settings
	 */
	USER_Setting: () => LocalizedString
	/**
	 * User ID
	 */
	USER_ID: () => LocalizedString
	/**
	 * Username
	 */
	USER_Username: () => LocalizedString
	/**
	 * First Name
	 */
	USER_FirstName: () => LocalizedString
	/**
	 * Last Name
	 */
	USER_LastName: () => LocalizedString
	/**
	 * Email
	 */
	USER_Email: () => LocalizedString
	/**
	 * Password
	 */
	USER_Password: () => LocalizedString
	/**
	 * New Password:
	 */
	USER_NewPassword: () => LocalizedString
	/**
	 * Edit User Settings
	 */
	USER_Edit: () => LocalizedString
	/**
	 * Email already in use
	 */
	USER_Fail: () => LocalizedString
	/**
	 * Delete
	 */
	USER_Delete: () => LocalizedString
	/**
	 * Cancel
	 */
	USER_Cancel: () => LocalizedString
	/**
	 * Save
	 */
	USER_Save: () => LocalizedString
	/**
	 * User Profile
	 */
	USER_Profile: () => LocalizedString
	/**
	 * Edit Avatar
	 */
	USER_Edit_Avatar: () => LocalizedString
	/**
	 * Role
	 */
	USER_Role: () => LocalizedString
	/**
	 * Email User Registration token
	 */
	USER_Generate: () => LocalizedString
	/**
	 * Show User List
	 */
	USER_ListShow: () => LocalizedString
	/**
	 * Collapse User List
	 */
	USER_ListCollapse: () => LocalizedString
	/**
	 * Email User Registration token
	 */
	USER_EmailToken: () => LocalizedString
	/**
	 * Token List:
	 */
	USER_ListToken: () => LocalizedString
	/**
	 * User List:
	 */
	USER_ListUser: () => LocalizedString
	/**
	 * Admin Area:
	 */
	USER_AdminArea: () => LocalizedString
	/**
	 * Edit User Data:
	 */
	USER_Edit_Title: () => LocalizedString
	/**
	 * Modify your data and then press Save.
	 */
	USER_Edit_Body: () => LocalizedString
	/**
	 * Edit your Avatar:
	 */
	USER_Avatar_Title: () => LocalizedString
	/**
	 * Upload new Avatar Image und then press Save.
	 */
	USER_Avatar_Body: () => LocalizedString
	/**
	 * File size must be less than 5MB
	 */
	USER_FileSize: () => LocalizedString
	/**
	 * PNG, JPEG, GIF, SVG, WEBP, AVIF allowed.
	 */
	USER_FilesAllowed: () => LocalizedString
	/**
	 * Supported formats: jpeg, jpg, png, webp, avif, svg, gif
	 */
	USER_Avatar_Unsupported: () => LocalizedString
	/**
	 * Please Confirm User Deletion:
	 */
	USER_Confirm_Title: () => LocalizedString
	/**
	 * This cannot be undone. Are you sure you wish to proceed?
	 */
	USER_Confirm_Body: () => LocalizedString
	/**
	 * Delete User
	 */
	USER_Confirm_Delete: () => LocalizedString
	/**
	 * List of User:
	 */
	TANSTACK_UserList: () => LocalizedString
	/**
	 * Columns
	 */
	TANSTACK_Column: () => LocalizedString
	/**
	 * All
	 */
	TANSTACK_Toggle: () => LocalizedString
	/**
	 * Facets Filters
	 */
	TANSTACK_Filter: () => LocalizedString
	/**
	 * XML Export
	 */
	TANSTACK_Export: () => LocalizedString
	/**
	 * Page
	 */
	TANSTACK_Page: () => LocalizedString
	/**
	 * of
	 */
	TANSTACK_of: () => LocalizedString
	/**
	 * Total
	 */
	TANSTACK_Total: () => LocalizedString
	/**
	 * Row
	 */
	TANSTACK_Row: () => LocalizedString
	/**
	 * Rows
	 */
	TANSTACK_Rows: () => LocalizedString
	/**
	 * Sign In
	 */
	LOGIN_SignIn: () => LocalizedString
	/**
	 * Sign Up
	 */
	LOGIN_SignUp: () => LocalizedString
	/**
	 * * Required
	 */
	LOGIN_Required: () => LocalizedString
	/**
	 * Username
	 */
	LOGIN_Username: () => LocalizedString
	/**
	 * Email Address
	 */
	LOGIN_EmailAddress: () => LocalizedString
	/**
	 * Password
	 */
	LOGIN_Password: () => LocalizedString
	/**
	 * Registration Token
	 */
	LOGIN_Token: () => LocalizedString
	/**
	 * Confirm Password
	 */
	LOGIN_ConfirmPassword: () => LocalizedString
	/**
	 * Forgotten Password
	 */
	LOGIN_ForgottenPassword: () => LocalizedString
	/**
	 * Do not worry. We will help you Recover your Password.
	 */
	LOGIN_ForgottenPassword_text: () => LocalizedString
	/**
	 * Send Password Reset Email
	 */
	LOGIN_SendResetMail: () => LocalizedString
	/**
	 * Reset Password
	 */
	LOGIN_ResetPassword: () => LocalizedString
	/**
	 * Save New Password
	 */
	LOGIN_ResetPasswordSave: () => LocalizedString
	/**
	 * Signed In Successfully
	 */
	LOGIN_SignInSuccess: () => LocalizedString
	/**
	 * Username is required
	 */
	LOGIN_ZOD_Username_string: () => LocalizedString
	/**
	 * Name can only contain letters, digits and @$!%*#
	 */
	LOGIN_ZOD_Username_regex: () => LocalizedString
	/**
	 * Name must be at least 2 characters
	 */
	LOGIN_ZOD_Username_min: () => LocalizedString
	/**
	 * Name can only be 24 characters
	 */
	LOGIN_ZOD_Username_max: () => LocalizedString
	/**
	 * Email is required
	 */
	LOGIN_ZOD_Email_string: () => LocalizedString
	/**
	 * Email must be a valid email
	 */
	LOGIN_ZOD_Email_email: () => LocalizedString
	/**
	 * Password is required
	 */
	LOGIN_ZOD_Password_string: () => LocalizedString
	/**
	 * Password must be a minimum of 8 characters & contain at least one letter, one number, and one special character.
	 */
	LOGIN_ZOD_Password_regex: () => LocalizedString
	/**
	 * Confirm Password is required
	 */
	LOGIN_ZOD_Confirm_password_string: () => LocalizedString
	/**
	 * Password must be a minimum of 8 characters & contain at least one letter, one number, and one special character.
	 */
	LOGIN_ZOD_Confirm_password_regex: () => LocalizedString
	/**
	 * Auth Token is required
	 */
	LOGIN_ZOD_Token_string: () => LocalizedString
	/**
	 * Password & Confirm password must match
	 */
	LOGIN_ZOD_Password_match: () => LocalizedString
	/**
	 * Unknown error occurred
	 */
	LOGIN_ZOD_General_Unknown: () => LocalizedString
	/**
	 * Invalid input
	 */
	LOGIN_ZOD_General_Error: () => LocalizedString
	/**
	 * Email already in use
	 */
	LOGIN_ZOD_Email_Error_inUse: () => LocalizedString
	/**
	 * Error sending mail
	 */
	LOGIN_ZOD_Email_Error_send: () => LocalizedString
	/**
	 * LOGIN_ZOD_Signup_unknown
	 */
	LOGIN_ZOD_Email_Error_Signup: () => LocalizedString
	/**
	 * Incorrect email or password.
	 */
	LOGIN_ZOD_Email_Error_SignupKey: () => LocalizedString
	/**
	 * Token is wrong!
	 */
	LOGIN_ZOD_Token_Error: () => LocalizedString
	/**
	 * Token has expired!
	 */
	LOGIN_ZOD_Token_Expired: () => LocalizedString
	/**
	 * No account under this email
	 */
	LOGIN_ZOD_Forgotten_Error: () => LocalizedString
	/**
	 * Hi there,<br><br>We received a request to reset your password. Your password reset token is:<br><br>{token}<br> <br>Please follow the link below to reset your password:<br>{link}<br><br>If you did not request this reset, please disregard this message.<br><br>Best regards,<br>The Support Team
	 */
	LOGIN_ZOD_Forgotten_email: (arg: { link: string, token: string }) => LocalizedString
	/**
	 * No Data
	 */
	ENTRYLIST_Untranslated: () => LocalizedString
	/**
	 * Create
	 */
	ENTRYLIST_Create: () => LocalizedString
	/**
	 * Publish
	 */
	ENTRYLIST_Publish: () => LocalizedString
	/**
	 * Unpublish
	 */
	ENTRYLIST_Unpublish: () => LocalizedString
	/**
	 * Schedule
	 */
	ENTRYLIST_Schedule: () => LocalizedString
	/**
	 * Clone
	 */
	ENTRYLIST_Clone: () => LocalizedString
	/**
	 * Delete
	 */
	ENTRYLIST_Delete: () => LocalizedString
	/**
	 * Please Confirm Deletion !!
	 */
	ENTRYLIST_Delete_title: () => LocalizedString
	/**
	 * Are you sure you wish to proceed?
	 */
	ENTRYLIST_Delete_body: () => LocalizedString
	/**
	 * Cancel
	 */
	ENTRYLIST_Delete_cancel: () => LocalizedString
	/**
	 * Confirm
	 */
	ENTRYLIST_Delete_confirm: () => LocalizedString
	/**
	 * Search
	 */
	ENTRYLIST_Search: () => LocalizedString
	/**
	 * Loading...
	 */
	ENTRYLIST_Loading: () => LocalizedString
	/**
	 * Please Confirm Content Creation
	 */
	ENTRYLIST_Modal_title_Create: () => LocalizedString
	/**
	 * Are you sure you wish to Create this content?
	 */
	ENTRYLIST_Modal_body_Create: () => LocalizedString
	/**
	 * Please Confirm Content Publication
	 */
	ENTRYLIST_Modal_title_Publish: () => LocalizedString
	/**
	 * Are you sure you wish to Publish this content?
	 */
	ENTRYLIST_Modal_body_Publish: () => LocalizedString
	/**
	 * Please Confirm Content Unpublish
	 */
	ENTRYLIST_Modal_title_Unpublish: () => LocalizedString
	/**
	 * Are you sure you wish to Unpublish this content?
	 */
	ENTRYLIST_Modal_body_Unpublish: () => LocalizedString
	/**
	 * Please Confirm Content Schedule
	 */
	ENTRYLIST_Modal_title_Schedule: () => LocalizedString
	/**
	 * Are you sure you wish to Schedule this content?
	 */
	ENTRYLIST_Modal_body_Schedule: () => LocalizedString
	/**
	 * Please Confirm Content Clone
	 */
	ENTRYLIST_Modal_title_Clone: () => LocalizedString
	/**
	 * Are you sure you wish to Clone this content?
	 */
	ENTRYLIST_Modal_body_Clone: () => LocalizedString
	/**
	 * Please Confirm Content Delete
	 */
	ENTRYLIST_Modal_title_Delete: () => LocalizedString
	/**
	 * Are you sure you wish to Delete this content?
	 */
	ENTRYLIST_Modal_body_Delete: () => LocalizedString
	/**
	 * Cancel
	 */
	ENTRYLIST_Modal_Cancel: () => LocalizedString
	/**
	 * Create
	 */
	FORM_Create: () => LocalizedString
	/**
	 * Close Menu
	 */
	FORM_CloseMenu: () => LocalizedString
	/**
	 * Close without saving
	 */
	FORM_TT_Closes: () => LocalizedString
	/**
	 * Required
	 */
	FORM_Required: () => LocalizedString
	/**
	 * User
	 */
	COLLECTION_TEST_User: () => LocalizedString
	/**
	 * Prefix
	 */
	COLLECTION_TEST_Prefix: () => LocalizedString
	COLLECTION_TEST_Prefix_data: {
		/**
		 * Mr.
		 */
		'0': () => LocalizedString
		/**
		 * Ms.
		 */
		'1': () => LocalizedString
		/**
		 * Mrs.
		 */
		'2': () => LocalizedString
		/**
		 * Dr.
		 */
		'3': () => LocalizedString
	}
	/**
	 * Enter Prefix
	 */
	COLLECTION_TEST_Prefix_placeholder: () => LocalizedString
	/**
	 * First
	 */
	COLLECTION_TEST_First: () => LocalizedString
	/**
	 * Enter First Name
	 */
	COLLECTION_TEST_First_placeholder: () => LocalizedString
	/**
	 * Middle
	 */
	COLLECTION_TEST_Middle: () => LocalizedString
	/**
	 * Middle  (ReadOnly)
	 */
	COLLECTION_TEST_Middle_placeholder: () => LocalizedString
	/**
	 * Last
	 */
	COLLECTION_TEST_Last: () => LocalizedString
	/**
	 * Enter Last Name
	 */
	COLLECTION_TEST_Last_placeholder: () => LocalizedString
	/**
	 * Full Text Option
	 */
	COLLECTION_TEST_Full_Text_Option: () => LocalizedString
	/**
	 * Enter full text
	 */
	COLLECTION_TEST_Full_Text_Option_Placeholder: () => LocalizedString
	/**
	 * Please enter a name for your menu before adding Menu Categories.
	 */
	WIDGET_MegaMenu_title: () => LocalizedString
	/**
	 * Next
	 */
	WIDGET_MegaMenu_Next: () => LocalizedString
	/**
	 * Search in Map ...
	 */
	WIDGET_Address_SearchMap: () => LocalizedString
	/**
	 * Get from Address
	 */
	WIDGET_Address_GetAddress: () => LocalizedString
	/**
	 * Get from Address
	 */
	WIDGET_Address_GetMap: () => LocalizedString
	/**
	 * Geo Coordinates
	 */
	WIDGET_Address_Geocoordinates: () => LocalizedString
	/**
	 * Latitude
	 */
	WIDGET_Address_Latitude: () => LocalizedString
	/**
	 * Longitude
	 */
	WIDGET_Address_Longitude: () => LocalizedString
	/**
	 * Name
	 */
	WIDGET_Address_Name: () => LocalizedString
	/**
	 * Street address
	 */
	WIDGET_Address_Street: () => LocalizedString
	/**
	 * ZIP or Postal Code
	 */
	WIDGET_Address_Zip: () => LocalizedString
	/**
	 * City
	 */
	WIDGET_Address_City: () => LocalizedString
	/**
	 * Search Country ...
	 */
	WIDGET_Address_SearchCountry: () => LocalizedString
	/**
	 * Chose existing...
	 */
	WIDGET_Relation_ChoseExisting: () => LocalizedString
	/**
	 * Edit
	 */
	WIDGET_Relation_Edit: () => LocalizedString
	/**
	 * Add New
	 */
	WIDGET_Relation_AddNew: () => LocalizedString
	/**
	 * Your title is more than 50 characters. Perfect!
	 */
	WIDGET_Seo_Suggestion_TitlePerfect: () => LocalizedString
	/**
	 * Your title is more than 30 characters. Try 50+. Good!
	 */
	WIDGET_Seo_Suggestion_TitleGood: () => LocalizedString
	/**
	 * Your title is too short. Make sure your title is at least 50 characters. Bad!
	 */
	WIDGET_Seo_Suggestion_TitleBad: () => LocalizedString
	/**
	 * Your description is between 120 and 165 characters. Perfect!
	 */
	WIDGET_Seo_Suggestion_DescriptionPerfect: () => LocalizedString
	/**
	 * Your description is more than 90 characters. Good!
	 */
	WIDGET_Seo_Suggestion_DescriptionGood: () => LocalizedString
	/**
	 * Your description is less than 90 characters. Bad!
	 */
	WIDGET_Seo_Suggestion_DescriptionBad: () => LocalizedString
	/**
	 * Your description is 2 to 4 sentences long. Perfect!
	 */
	WIDGET_Seo_Suggestion_SentencePerfect: () => LocalizedString
	/**
	 * Your description is 2 to 4 sentences long but not all sentences are between 10 and 30 characters. Good!
	 */
	WIDGET_Seo_Suggestion_SentenceGood: () => LocalizedString
	/**
	 * Your description is only 1 sentence long. Make sure your description is 2 to 4 sentences long.
	 */
	WIDGET_Seo_Suggestion_SentenceBad: () => LocalizedString
	/**
	 * Your title uses numbers. Perfect!
	 */
	WIDGET_Seo_Suggestion_NumberPerfect: () => LocalizedString
	/**
	 * Your title does not use numbers. The use of numbers in your title can increase your CTR.
	 */
	WIDGET_Seo_Suggestion_NumberBad: () => LocalizedString
	/**
	 * Your title has the Power Word. Perfect!
	 */
	WIDGET_Seo_Suggestion_PowerWordTitle: () => LocalizedString
	/**
	 * Your title does not have a Power Word. Bad!
	 */
	WIDGET_Seo_Suggestion_PowerWordTitleBad: () => LocalizedString
	/**
	 * Your description uses the Power Word. Perfect!
	 */
	WIDGET_Seo_Suggestion_PowerWordDescription: () => LocalizedString
	/**
	 * Your description does not use a Power Word. Bad
	 */
	WIDGET_Seo_Suggestion_PowerWordDescriptionBad: () => LocalizedString
	/**
	 * Your title has the CTA keyword. Perfect!
	 */
	WIDGET_Seo_Suggestion_ctaKeywordsTitle: () => LocalizedString
	/**
	 * Your title does not have a CTA keyword. Bad!
	 */
	WIDGET_Seo_Suggestion_ctaKeywordsTitleBad: () => LocalizedString
	/**
	 * Your description uses the CTA keyword. Perfect!
	 */
	WIDGET_Seo_Suggestion_ctaKeywordsDescription: () => LocalizedString
	/**
	 * Your description does not use a CTA keyword. Bad!
	 */
	WIDGET_Seo_Suggestion_ctaKeywordsDescriptionBad: () => LocalizedString
	/**
	 * Title:
	 */
	WIDGET_Seo_Suggestion_Title: () => LocalizedString
	/**
	 * Character:
	 */
	WIDGET_Seo_Suggestion_Character: () => LocalizedString
	/**
	 * - Desktop:
	 */
	WIDGET_Seo_Suggestion_WidthDesktop: () => LocalizedString
	/**
	 * Mobile: 
	 */
	WIDGET_Seo_Suggestion_WidthMobile: () => LocalizedString
	/**
	 * SEO Title: 
	 */
	WIDGET_Seo_Suggestion_SeoTitle: () => LocalizedString
	/**
	 * Description:
	 */
	WIDGET_Seo_Suggestion_Description: () => LocalizedString
	/**
	 * SEO Description
	 */
	WIDGET_Seo_Suggestion_SeoDescription: () => LocalizedString
	/**
	 * SEO Preview
	 */
	WIDGET_Seo_Suggestion_SeoPreview: () => LocalizedString
	/**
	 * SEO Suggestions:
	 */
	WIDGET_Seo_Suggestion_ListOfSuggestion: () => LocalizedString
	/**
	 * Optimize title & description for Google search results, to improve the visual appeal to brings more clicks to your website.
	 */
	WIDGET_Seo_Suggestion_Text: () => LocalizedString
	WIDGET_SEO_PowerWords: {
		/**
		 * amazing
		 */
		'0': () => LocalizedString
		/**
		 * attractive
		 */
		'1': () => LocalizedString
		/**
		 * become
		 */
		'2': () => LocalizedString
		/**
		 * best
		 */
		'3': () => LocalizedString
		/**
		 * boost
		 */
		'4': () => LocalizedString
		/**
		 * breaking
		 */
		'5': () => LocalizedString
		/**
		 * breaking news
		 */
		'6': () => LocalizedString
		/**
		 * cheap
		 */
		'7': () => LocalizedString
		/**
		 * discover
		 */
		'8': () => LocalizedString
		/**
		 * direct
		 */
		'9': () => LocalizedString
		/**
		 * easy
		 */
		'10': () => LocalizedString
		/**
		 * exclusive
		 */
		'11': () => LocalizedString
		/**
		 * fresh
		 */
		'12': () => LocalizedString
		/**
		 * full
		 */
		'13': () => LocalizedString
		/**
		 * free
		 */
		'14': () => LocalizedString
		/**
		 * free trial
		 */
		'15': () => LocalizedString
		/**
		 * gain
		 */
		'16': () => LocalizedString
		/**
		 * get
		 */
		'17': () => LocalizedString
		/**
		 * grow
		 */
		'18': () => LocalizedString
		/**
		 * hurry
		 */
		'19': () => LocalizedString
		/**
		 * happiness
		 */
		'20': () => LocalizedString
		/**
		 * health
		 */
		'21': () => LocalizedString
		/**
		 * hot
		 */
		'22': () => LocalizedString
		/**
		 * improve
		 */
		'23': () => LocalizedString
		/**
		 * improvement
		 */
		'24': () => LocalizedString
		/**
		 * innovative
		 */
		'25': () => LocalizedString
		/**
		 * instant
		 */
		'26': () => LocalizedString
		/**
		 * join
		 */
		'27': () => LocalizedString
		/**
		 * latest
		 */
		'28': () => LocalizedString
		/**
		 * limited
		 */
		'29': () => LocalizedString
		/**
		 * limited time
		 */
		'30': () => LocalizedString
		/**
		 * love
		 */
		'31': () => LocalizedString
		/**
		 * new
		 */
		'32': () => LocalizedString
		/**
		 * newsworthy
		 */
		'33': () => LocalizedString
		/**
		 * powerful
		 */
		'34': () => LocalizedString
		/**
		 * popular
		 */
		'35': () => LocalizedString
		/**
		 * proven
		 */
		'36': () => LocalizedString
		/**
		 * quality
		 */
		'37': () => LocalizedString
		/**
		 * quick
		 */
		'38': () => LocalizedString
		/**
		 * revolutionary
		 */
		'39': () => LocalizedString
		/**
		 * save
		 */
		'40': () => LocalizedString
		/**
		 * sale
		 */
		'41': () => LocalizedString
		/**
		 * safety
		 */
		'42': () => LocalizedString
		/**
		 * sign up
		 */
		'43': () => LocalizedString
		/**
		 * special
		 */
		'44': () => LocalizedString
		/**
		 * special offer
		 */
		'45': () => LocalizedString
		/**
		 * solutions
		 */
		'46': () => LocalizedString
		/**
		 * success
		 */
		'47': () => LocalizedString
		/**
		 * support
		 */
		'48': () => LocalizedString
		/**
		 * today
		 */
		'49': () => LocalizedString
		/**
		 * trending
		 */
		'50': () => LocalizedString
		/**
		 * trust
		 */
		'51': () => LocalizedString
		/**
		 * urgent
		 */
		'52': () => LocalizedString
		/**
		 * viral
		 */
		'53': () => LocalizedString
		/**
		 * when
		 */
		'54': () => LocalizedString
		/**
		 * winner
		 */
		'55': () => LocalizedString
		/**
		 * worldwide
		 */
		'56': () => LocalizedString
		/**
		 * wealth
		 */
		'57': () => LocalizedString
	}
	WIDGET_SEO_ctaKeywords: {
		/**
		 * Act
		 */
		'0': () => LocalizedString
		/**
		 * Buy
		 */
		'1': () => LocalizedString
		/**
		 * Call
		 */
		'2': () => LocalizedString
		/**
		 * Click
		 */
		'3': () => LocalizedString
		/**
		 * Contact
		 */
		'4': () => LocalizedString
		/**
		 * Discover
		 */
		'5': () => LocalizedString
		/**
		 * Download
		 */
		'6': () => LocalizedString
		/**
		 * Find
		 */
		'7': () => LocalizedString
		/**
		 * Get
		 */
		'8': () => LocalizedString
		/**
		 * Join
		 */
		'9': () => LocalizedString
		/**
		 * Learn
		 */
		'10': () => LocalizedString
		/**
		 * Order
		 */
		'11': () => LocalizedString
		/**
		 * Register
		 */
		'12': () => LocalizedString
		/**
		 * Request
		 */
		'13': () => LocalizedString
		/**
		 * See
		 */
		'14': () => LocalizedString
		/**
		 * Sell
		 */
		'15': () => LocalizedString
		/**
		 * Sign-up
		 */
		'16': () => LocalizedString
		/**
		 * Subscribe
		 */
		'17': () => LocalizedString
		/**
		 * Try
		 */
		'18': () => LocalizedString
		/**
		 * View
		 */
		'19': () => LocalizedString
	}
}

export type Formatters = {}
