<script lang="ts">
	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';
	import { authAdapter, initializationPromise } from '@src/databases/db';
	import type { Role, Permission } from '@src/auth/types';

	let roles = writable<Role[]>([]);
	let selectedRoles = writable<Set<string>>(new Set());
	let roleName = '';
	let roleDescription = '';
	let availablePermissions = writable<Permission[]>([]);
	let selectedPermissions = writable<Set<string>>(new Set());
	let isLoading = writable(true);
	let error = writable<string | null>(null);

	onMount(async () => {
		try {
			await initializationPromise;
			await loadRoles();
			await loadPermissions();
		} catch (err) {
			error.set(`Failed to initialize: ${err instanceof Error ? err.message : String(err)}`);
		} finally {
			isLoading.set(false);
		}
	});

	const loadRoles = async () => {
		if (!authAdapter) {
			throw new Error('Auth adapter is not initialized');
		}
		try {
			const rolesData = await authAdapter.getAllRoles();
			roles.set(rolesData);
		} catch (err) {
			throw new Error(`Failed to load roles: ${err instanceof Error ? err.message : String(err)}`);
		}
	};

	const loadPermissions = async () => {
		if (!authAdapter) {
			throw new Error('Auth adapter is not initialized');
		}
		try {
			const permissionsData = await authAdapter.getAllPermissions();
			availablePermissions.set(permissionsData);
		} catch (err) {
			throw new Error(`Failed to load permissions: ${err instanceof Error ? err.message : String(err)}`);
		}
	};

	const addRole = async () => {
		if (!authAdapter) {
			throw new Error('Auth adapter is not initialized');
		}
		if (!roleName) return;

		const roleData: Role = {
			role_id: '', // This will be generated by the database
			name: roleName,
			description: roleDescription,
			permissions: Array.from($selectedPermissions)
		};

		try {
			await authAdapter.createRole(roleData);
			roleName = '';
			roleDescription = '';
			selectedPermissions.set(new Set());
			await loadRoles();
		} catch (err) {
			throw new Error(`Failed to add role: ${err instanceof Error ? err.message : String(err)}`);
		}
	};

	const deleteSelectedRoles = async () => {
		if (!authAdapter) {
			throw new Error('Auth adapter is not initialized');
		}
		try {
			for (const roleId of $selectedRoles) {
				await authAdapter.deleteRole(roleId);
			}
			selectedRoles.set(new Set());
			await loadRoles();
		} catch (err) {
			throw new Error(`Failed to delete roles: ${err instanceof Error ? err.message : String(err)}`);
		}
	};

	const toggleRoleSelection = (roleId: string) => {
		selectedRoles.update((selected) => {
			if (selected.has(roleId)) {
				selected.delete(roleId);
			} else {
				selected.add(roleId);
			}
			return selected;
		});
	};

	const togglePermissionSelection = (permissionId: string) => {
		selectedPermissions.update((selected) => {
			if (selected.has(permissionId)) {
				selected.delete(permissionId);
			} else {
				selected.add(permissionId);
			}
			return selected;
		});
	};
</script>

{#if $isLoading}
	<p>Loading...</p>
{:else if $error}
	<p class="error">{$error}</p>
{:else}
	<div class="my-4">
		<h3 class="text-lg font-semibold">Roles Management</h3>
		<div class="mb-4">
			<input type="text" bind:value={roleName} placeholder="Role Name" class="mb-2 w-full rounded border p-2" />
			<textarea bind:value={roleDescription} placeholder="Role Description" class="mb-2 w-full rounded border p-2"></textarea>
			<div class="flex flex-wrap gap-2">
				{#each $availablePermissions as permission (permission.permission_id)}
					<label class="flex items-center">
						<input
							type="checkbox"
							checked={$selectedPermissions.has(permission.permission_id)}
							on:change={() => togglePermissionSelection(permission.permission_id)}
							class="mr-2"
						/>
						<span>{permission.name}</span>
					</label>
				{/each}
			</div>
			<button on:click={addRole} class="mt-2 rounded bg-blue-500 px-4 py-2 text-white">Add Role</button>
			<button on:click={deleteSelectedRoles} class="ml-2 mt-2 rounded bg-red-500 px-4 py-2 text-white">Delete Selected Roles</button>
		</div>

		<div class="mt-4">
			<h4 class="mb-2">Existing Roles</h4>
			{#if $roles.length === 0}
				<p>No roles defined yet.</p>
			{:else}
				<ul class="list-disc pl-5">
					{#each $roles as role (role.role_id)}
						<li class="flex items-center">
							<input type="checkbox" checked={$selectedRoles.has(role.role_id)} on:change={() => toggleRoleSelection(role.role_id)} class="mr-2" />
							{role.name} - {role.description}
							<ul class="ml-4">
								{#each role.permissions as permissionId}
									<li>{$availablePermissions.find((p) => p.permission_id === permissionId)?.name || permissionId}</li>
								{/each}
							</ul>
						</li>
					{/each}
				</ul>
			{/if}
		</div>
	</div>
{/if}
