/**
 * @file src/widgets/custom/AIEnrichment/tests/ai-enrichment.test.ts
 * @description Unit tests for the AI Enrichment widget validation logic.
 */

import { describe, it, expect } from "bun:test";
import AIEnrichmentWidget from "../index";
import { safeParse } from "valibot";

describe("AI Enrichment Widget - Validation", () => {
  it("should validate string data when not translated", () => {
    const field = AIEnrichmentWidget({ label: "Summary", translated: false });
    const schema = (field.widget.validationSchema as any)(field);

    expect(safeParse(schema, "A summary generated by AI").success).toBe(true);
    expect(safeParse(schema, "").success).toBe(true);
    expect(safeParse(schema, undefined).success).toBe(true);
  });

  it("should validate record of strings when translated", () => {
    const field = AIEnrichmentWidget({ label: "Summary", translated: true });
    const schema = (field.widget.validationSchema as any)(field);

    const translatedData = {
      en: "English summary",
      de: "Deutche Zusammenfassung",
    };

    expect(safeParse(schema, translatedData).success).toBe(true);
    expect(safeParse(schema, {}).success).toBe(true);
  });

  it("should reject non-string data when not translated", () => {
    const field = AIEnrichmentWidget({ label: "Summary", translated: false });
    const schema = (field.widget.validationSchema as any)(field);

    expect(safeParse(schema, 123).success).toBe(false);
    expect(safeParse(schema, { key: "val" }).success).toBe(false);
  });

  it("should reject non-record data when translated", () => {
    const field = AIEnrichmentWidget({ label: "Summary", translated: true });
    const schema = (field.widget.validationSchema as any)(field);

    expect(safeParse(schema, "not-a-record").success).toBe(false);
    expect(safeParse(schema, 123).success).toBe(false);
  });
});
