<!--
@file src/routes/(app)/dashboard/GenerativeDashboard.svelte
@component
**AI-Native Generative Dashboard Wrapper**

This component acts as an intercept layer. It either renders a fully dynamic JSON spec
(supplied via an MCP server integration) or falls back to the manual widget grid.

### Features
- **AI-Native**: Renders JSON specs generated by AI agents.
- **Dynamic**: Supports dynamic JSON specs.
- **Fallback**: Falls back to manual widget grid if no JSON spec is provided.
-->

<script lang="ts">
	import { Renderer, JSONUIProvider, type Spec } from 'json-render-svelte';
	import { sveltyRegistry } from '@src/services/json-render/catalog';
	import type { Snippet } from 'svelte';

	interface Props {
		spec?: Spec | null;
		context?: Record<string, unknown>;
		children?: Snippet;
	}

	let { spec = null, context = {}, children }: Props = $props();
</script>

<div class="generative-dashboard-container w-full h-full animate-fade-in relative">
	{#if spec}
		<!-- AI Driven Layout -->
		<div
			class="ai-mode-badge absolute top-0 left-1/2 -translate-x-1/2 z-10 preset-filled-primary-500 badge rounded-b text-xs font-semibold py-1 px-3 shadow"
		>
			<iconify-icon icon="mdi:robot-outline" class="mr-1"></iconify-icon>
			AI Dashboard Mode
		</div>
		<div class="p-4 pt-8">
			<JSONUIProvider initialState={context}>
				<Renderer registry={sveltyRegistry} {spec} />
			</JSONUIProvider>
		</div>
	{:else if children}
		<!-- Manual Grid Fallback -->
		{@render children()}
	{/if}
</div>

<style>
	.animate-fade-in {
		animation: fadeIn 0.4s ease-out;
	}

	@keyframes fadeIn {
		from {
			opacity: 0;
			transform: scale(0.98);
		}
		to {
			opacity: 1;
			transform: scale(1);
		}
	}
</style>
