/**
 * @fileoverview Global i18n configuration using Paraglide JS
 * 
 * Provides type-safe, compile-time optimized translations with zero runtime overhead.
 * Each workspace can have its own message files while sharing global translations.
 * 
 * @module @shared/paraglide
 */

// Runtime functions
export { setLanguageTag, languageTag } from './runtime';

// Message functions (generated by Paraglide compiler)
// These will be generated after running: nx run paraglide:compile
export * from './messages';

/**
 * Available language tags
 */
export const availableLanguageTags = ['en', 'de', 'fr', 'es'] as const;

/**
 * Source language tag
 */
export const sourceLanguageTag = 'en' as const;

/**
 * Type for language tags
 */
export type LanguageTag = typeof availableLanguageTags[number];

/**
 * Placeholder runtime functions
 * Will be replaced with actual Paraglide runtime after compilation
 */
let currentLanguage: LanguageTag = 'en';

/**
 * Get current language tag
 */
export function languageTag(): LanguageTag {
  return currentLanguage;
}

/**
 * Set current language tag
 * @param tag - Language tag to set
 */
export function setLanguageTag(tag: LanguageTag): void {
  if (!availableLanguageTags.includes(tag)) {
    throw new Error(`Invalid language tag: ${tag}`);
  }
  currentLanguage = tag;
}

/**
 * Placeholder message functions
 * These will be generated by Paraglide compiler
 */
export const m = {
  common_save: () => 'Save',
  common_cancel: () => 'Cancel',
  common_delete: () => 'Delete',
  common_edit: () => 'Edit',
  common_close: () => 'Close',
  common_search: () => 'Search',
  common_loading: () => 'Loading...',
  
  errors_generic: () => 'An error occurred',
  errors_network: () => 'Network error',
  errors_unauthorized: () => 'Unauthorized access',
  errors_notFound: () => 'Not found',
  
  validation_required: () => 'This field is required',
  validation_email: () => 'Invalid email address',
  validation_minLength: (params: { min: number }) => `Minimum ${params.min} characters required`,
  validation_maxLength: (params: { max: number }) => `Maximum ${params.max} characters allowed`
};
