/**
 * @file tests/integration/harness.ts
 * @description
 * Singleton integration server lifecycle harness.
 *
 * Provides a module-level promise so multiple parallel test files waiting for
 * the same server share one startup sequence.  Auto-registers process.exit
 * cleanup so the preview process does not orphan.
 *
 * ### Usage (indirect)
 * Tests call `waitForServer()` from `tests/integration/helpers/server.ts`,
 * which delegates to `startIntegrationServer()` if the server is not already
 * healthy.  No per-test-file changes are needed.
 *
 * ### Features:
 * - singleton startup promise (parallel-safe)
 * - config/private.test.ts auto-generation
 * - health-check polling with DB-migration settle detection
 * - /api/testing seed after boot
 * - process.exit cleanup guard
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { getDockerDefaultDbCredentials } from "../../src/utils/test-db-credentials.ts";
import { isConfigSourceSafeForTesting } from "../../src/utils/test-db-safety.ts";
import { isCiRunner } from "../../src/utils/private-config-policy.ts";

// ── Derived paths ───────────────────────────────────────────────────────────

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const PORT = process.env.PORT ?? "4173";
const HOST = process.env.HOST ?? "127.0.0.1";
const API_BASE_URL = process.env.API_BASE_URL ?? `http://${HOST}:${PORT}`;

// ── Module-level state (singleton) ───────────────────────────────────────────

/** Singleton promise: once resolved the server is fully started and seeded. */
let serverPromise: Promise<void> | null = null;

// ── Internal helpers ─────────────────────────────────────────────────────────

function getEnvValue(name: string): string | undefined {
  if (Object.prototype.hasOwnProperty.call(process.env, name)) {
    return process.env[name];
  }
  return undefined;
}

function getDbDefaults() {
  const dbType = process.env.DB_TYPE || "sqlite";
  const defaultPort =
    dbType === "postgresql"
      ? "5432"
      : dbType === "mariadb"
        ? "3306"
        : dbType === "mongodb"
          ? "27017"
          : "";

  const dbPort = getEnvValue("DB_PORT") ?? defaultPort;
  const defaults = getDockerDefaultDbCredentials(dbType);
  const dbUser = getEnvValue("DB_USER") ?? defaults.user;
  const dbPassword = getEnvValue("DB_PASSWORD") ?? defaults.password;

  return {
    type: dbType,
    host: getEnvValue("DB_HOST") ?? "127.0.0.1",
    port: dbPort,
    name: getEnvValue("DB_NAME") ?? "sveltycms_test",
    user: dbUser,
    password: dbPassword,
  };
}

function generatePrivateTestConfig(privateTestPath: string) {
  const db = getDbDefaults();
  const dbPortValue =
    db.type === "sqlite" || !db.port ? "undefined" : String(Number.parseInt(db.port, 10));

  const jwt = process.env.JWT_SECRET_KEY || "Integration-Test-JWT-Secret-Key-2026";
  const enc = process.env.ENCRYPTION_KEY || "Integration-Encryption-Key-2026-32ch";
  const testSecret = process.env.TEST_API_SECRET || "SVELTYCMS_TEST_SECRET_2026";

  const content = `/**
 * Auto-generated test config for integration tests.
 * This is generated by tests/integration/harness.ts
 */
export const privateEnv = {
  DB_TYPE: "${db.type}",
  DB_HOST: "${db.host}",
  DB_PORT: ${dbPortValue},
  DB_NAME: "${db.name}",
  DB_USER: "${db.user}",
  DB_PASSWORD: "${db.password}",
  JWT_SECRET_KEY: "${jwt}",
  ENCRYPTION_KEY: "${enc}",
  TEST_API_SECRET: "${testSecret}",
  PASSWORD_MIN_LENGTH: 8,
  USE_REDIS: false,
  REDIS_HOST: "127.0.0.1",
  REDIS_PORT: 6379,
  MULTI_TENANT: false,
  DEMO: false,
  HOST_PROD: "${API_BASE_URL}"
};
export const privateConfig = privateEnv;
export default privateEnv;
`;

  writeFileSync(privateTestPath, content, "utf8");
  console.log("✅ Generated config/private.test.ts from integration test harness");
}

function ensurePrivateTestConfig() {
  const configDir = join(ROOT, "config");
  const privateTestPath = join(configDir, "private.test.ts");
  const privatePath = join(configDir, "private.ts");
  const isCI = isCiRunner();

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  if (isCI) {
    generatePrivateTestConfig(privateTestPath);
    copyFileSync(privateTestPath, privatePath);
    console.log("✅ [CI] Mirrored config/private.test.ts → config/private.ts (ephemeral)");
    console.log(`✅ Test config verified: ${privateTestPath}`);
    return;
  }

  // LOCAL: never create, overwrite, rename, or delete config/private.ts.
  if (existsSync(privateTestPath)) {
    const existing = readFileSync(privateTestPath, "utf8");
    const { safe } = isConfigSourceSafeForTesting(existing);
    if (!safe) {
      console.warn(
        "⚠️ config/private.test.ts has an unsafe DB_NAME. Regenerating safe test config.",
      );
      generatePrivateTestConfig(privateTestPath);
    }
  }

  if (!existsSync(privateTestPath)) {
    generatePrivateTestConfig(privateTestPath);
  }

  if (!existsSync(privateTestPath)) {
    throw new Error(`System setup did not create required test config: ${privateTestPath}`);
  }

  console.log(`✅ LOCAL test config: ${privateTestPath} (config/private.ts left untouched)`);
}

async function waitForServerReady(maxAttempts = 60): Promise<boolean> {
  console.log("⏳ Waiting for server to reach READY state...");

  const targetStates = new Set([
    "ready",
    "healthy",
    "ok",
    "degraded",
    "setup",
    "idle",
    "initializing",
  ]);
  const testApiSecret = process.env.TEST_API_SECRET || "SVELTYCMS_TEST_SECRET_2026";

  for (let i = 0; i < maxAttempts; i++) {
    try {
      const res = await fetch(`${API_BASE_URL}/api/system/health`, {
        headers: {
          "x-test-mode": "true",
          "x-test-secret": testApiSecret,
        },
        signal: AbortSignal.timeout(3000),
      });

      if (res.status === 503) {
        const retryAfter = res.headers.get("retry-after");
        if (retryAfter) {
          const delay = Number(retryAfter) * 1000 || 2000;
          await new Promise((r) => setTimeout(r, delay));
          continue;
        }
      }

      if (res.ok || res.status === 533) {
        const data = await res.json().catch(() => ({}));
        const payload = data?.data && typeof data.data === "object" ? data.data : data;
        const rawStatus = (payload.overallStatus || payload.status || payload.health || "")
          .toString()
          .toLowerCase();
        const dbStatus = String(payload.database || "").toLowerCase();

        if (targetStates.has(rawStatus)) {
          console.log(`✅ Server is up (state: ${rawStatus}, db: ${dbStatus || "n/a"})`);

          if (rawStatus === "setup" || rawStatus === "idle") {
            if (dbStatus === "connected" || dbStatus === "healthy" || i >= 5) {
              return true;
            }
          }

          console.log("⏳ Waiting for database migrations to settle...");
          for (let settle = 0; settle < 15; settle++) {
            await new Promise((r) => setTimeout(r, 1000));
            try {
              const settleRes = await fetch(`${API_BASE_URL}/api/system/health`, {
                headers: {
                  "x-test-mode": "true",
                  "x-test-secret": testApiSecret,
                  "x-refresh": "true",
                },
                signal: AbortSignal.timeout(3000),
              });
              if (settleRes.ok) {
                const settleData = await settleRes.json().catch(() => ({}));
                const db = settleData?.database ?? settleData?.data?.database ?? "";
                if (db === "connected" || db === true) {
                  console.log("✅ Database migrations settled.");
                  return true;
                }
              }
            } catch {
              /* still settling */
            }
          }
          console.log("⚠️ Database migrations did not settle — proceeding anyway.");
          return true;
        }

        console.log(`⏳ Server state: ${rawStatus} (${i + 1}/${maxAttempts})...`);
      }
    } catch {
      /* server not listening yet */
    }
    await new Promise((resolve) => setTimeout(resolve, 1000));
  }

  console.log("⚠️ Server did not reach READY state within timeout.");
  return false;
}

async function ensureServerRunning(): Promise<void> {
  // Server must be started BEFORE bun test by scripts/start-integration-server.ts
  const ready = await waitForServerReady(15); // shorter timeout — server should already be starting
  if (!ready) {
    console.error(
      "\n❌ Server not running at http://127.0.0.1:4173." +
        "\n   Start it first with: bun run scripts/start-integration-server.ts" +
        "\n   Or run: bun run test:integration (which handles it automatically)\n",
    );
    throw new Error("Integration server not running");
  }
}

async function testingAction(action: "reset" | "seed", preset?: string): Promise<void> {
  let lastError: Error | null = null;
  const maxRetries = 5;
  const testApiSecret = process.env.TEST_API_SECRET || "SVELTYCMS_TEST_SECRET_2026";

  for (let i = 0; i < maxRetries; i++) {
    try {
      const body: Record<string, unknown> = { action };
      if (action === "seed") {
        body.email = process.env.ADMIN_EMAIL || "admin@example.com";
        body.password = process.env.ADMIN_PASSWORD || "Password123!";
      }
      if (preset) body.preset = preset;

      const response = await fetch(`${API_BASE_URL}/api/testing`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-test-mode": "true",
          "x-test-secret": testApiSecret,
          Origin: API_BASE_URL,
        },
        body: JSON.stringify(body),
      });

      if (response.ok) return;

      const text = await response.text().catch(() => "");
      if (response.status === 503 && i < maxRetries - 1) {
        console.log(`/api/testing ${action} returned 503 (initializing). Retrying in 2s...`);
        await new Promise((resolve) => setTimeout(resolve, 2000));
        continue;
      }

      console.error(
        `/api/testing ${action} FAILED (HTTP ${response.status}): ${text.slice(0, 500)}`,
      );
      throw new Error(
        `/api/testing ${action} failed with HTTP ${response.status}: ${text.slice(0, 300)}`,
      );
    } catch (err: any) {
      lastError = err;
      if (i < maxRetries - 1) {
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    }
  }

  throw lastError || new Error(`Failed /api/testing ${action} after ${maxRetries} retries`);
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Ensures the integration preview server is running (singleton).
 *
 * Server is started BEFORE bun test by scripts/start-integration-server.ts or
 * bun run test:integration. This function only waits for it to be ready and
 * seeds the database.
 *
 * 1. Ensures config/private.test.ts exists
 * 2. Waits for health-check success
 * 3. Seeds the database via /api/testing action "seed"
 */
export async function startIntegrationServer(): Promise<void> {
  if (serverPromise) return serverPromise;

  serverPromise = (async () => {
    try {
      ensurePrivateTestConfig();
      await ensureServerRunning();
      await testingAction("seed");
      console.log("✅ Integration server seeded and ready for tests.");
    } catch (err) {
      // Reset promise so a subsequent call can retry after failure
      serverPromise = null;
      throw err;
    }
  })();

  return serverPromise;
}

/**
 * Stops the integration preview server if it is running.
 * Safe to call multiple times. Server is managed by scripts/start-integration-server.ts
 * which handles cleanup via process exit, so this is a no-op.
 */
export async function stopIntegrationServer(): Promise<void> {
  // Server lifecycle managed by scripts/start-integration-server.ts — no-op
  serverPromise = null;
}
