// The user table stores the users
import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema(
	{
		// Will be generated by Lucia
		_id: {
			type: String
		},

		// Other User Properties
		email: String,
		role: String,
		username: String,
		firstname: String,
		lastname: String,
		avatar: String,
		resetRequestedAt: String,
		resetToken: String,
		expiresAt: Date,
	},

	// Let Lucia handle the _id field
	{ _id: false }
);

let User: mongoose.Model<any> = null as any;

if (mongoose.models && mongoose.models.user) {
	mongoose.deleteModel('user');
}

User = mongoose.model('user', UserSchema);

// Check if the first user exists in the database
let firstUserExists = false;
// Use then() and catch() to handle the result and error
User.findOne({})
	.then((user) => {
		// Check if user is not null
		firstUserExists = !!user;
	})
	.catch((err) => {
		console.error(err);
	});
export { firstUserExists, User };
