/**
 * @file apps/cms/src/stores/system/index.ts
 * @description CMS-level re-export of shared system stores.
 */

export {
	initialState,
	systemStateStore,
	systemState,
	overallState,
	isReady,
	isInitializing,
	isDegraded,
	isFailed,
	servicesStatus,
	databaseStatus,
	authStatus,
	cacheStatus,
	contentManagerStatus,
	themeManagerStatus,
	getSystemState,
	setSystemState,
	setInitializationStage,
	updateServiceHealth,
	isServiceHealthy,
	isSystemReady,
	resetSystemState,
	startServiceInitialization,
	resetCircuitBreaker,
	getSystemMetrics,
	systemEvents,
	trackStateTransition,
	waitForSystemReady,
	waitForServiceHealthy,
	detectAnomalies,
	calibrateAnomalyThresholds,
	updateUptimeMetrics,
	getHealthCheckReport,
	getPerformanceSummary,
	getRecommendedTimeouts,
	identifyBottlenecks,
	type InitializationStage,
	type ServiceHealth,
	type ServiceName,
	type ServicesMap,
	type SystemState,
	type AnomalyDetection,
	type AnomalyThresholds,
	type ServiceCircuitBreaker,
	type ServicePerformanceMetrics,
	type ServiceStatus,
	type StateTimingMetrics,
	type SystemPerformanceMetrics,
	type SystemStateStore
} from '@shared/stores';
