// Auto-generated by svelte-realtime - do not edit
// Provides client-side types for $live/ imports

declare module "$live/chat" {
  import type { StreamStore, RpcError } from "svelte-realtime/client";
  import type { Readable } from "svelte/store";

  export const sendMessage: ({ content, room, history = [] }: any) => Promise<any>;
  export const chat: ((room: string) => StreamStore<any | undefined | { error: RpcError }>) & {
    load(platform: any, options?: { args?: any[]; user?: any }): Promise<any>;
  };
  export const empty: Readable<undefined>;
}

declare module "$live/system" {
  import type { StreamStore, RpcError } from "svelte-realtime/client";
  import type { Readable } from "svelte/store";

  export const events: StreamStore<any | undefined | { error: RpcError }> & {
    load(platform: any, options?: { args?: any[]; user?: any }): Promise<any>;
  };
  export const empty: Readable<undefined>;
}
