// Auto-generated by svelte-realtime - do not edit
// Provides client-side types for $live/ imports

declare module '$live/chat' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const sendMessage: (payload: SendMessagePayload) => Promise<any>;
  export const chat: ((room?: string) => StreamStore<ChatMessage[] | undefined | { error: RpcError }>) & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<ChatMessage[]> };
  export const empty: Readable<undefined>;
}

declare module '$live/system' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const events: StreamStore<SystemEvent[] | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<SystemEvent[]> };
  export const empty: Readable<undefined>;
}
