/**
 * @file scripts/enterprise-matrix.ts
 * @description Zero-Mock Enterprise Production Performance Audit.
 * Enhanced version: Better types, robust cleanup, structured logging, reliable readiness checks.
 */

import { spawn, type ChildProcess } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { pc } from "../src/utils/native-utils";

interface DatabaseConfig {
  type: string;
  port: number | null;
  host: string;
}

interface BenchmarkResult {
  db: string;
  cache: "Redis" | "Memory";
  status: "SUCCESS" | "FAILED";
  coldStartMs?: number;
  metrics?: Record<string, any>;
  error?: string;
}

const DATABASES: DatabaseConfig[] = [
  { type: "sqlite", port: null, host: "./config/database" },
  { type: "mongodb", port: 27017, host: "127.0.0.1" },
  { type: "postgresql", port: 5432, host: "127.0.0.1" },
  { type: "mariadb", port: 3306, host: "127.0.0.1" },
];

const BASE_PORT = 4173;
const TEST_API_SECRET = "enterprise-audit-2026";
// Use private.test.ts to avoid stomping on developer's local dev config
const CONFIG_PATH = path.join(process.cwd(), "config/private.test.ts");
const CONFIG_BACKUP_PATH = path.join(process.cwd(), "config/private.test.ts.bak");
const RESULTS_DIR = path.join(process.cwd(), "tests/benchmarks/results");
const BENCHMARKS_DOC = path.join(process.cwd(), "docs/project/benchmarks.mdx");

let serverProcess: ChildProcess | null = null;
let originalConfigExisted = false;
let startTime: number;

const log = {
  info: (msg: string) => console.log(`${pc.blue("[INFO]")} ${msg}`),
  success: (msg: string) => console.log(`✅ ${pc.green(msg)}`),
  warn: (msg: string) => console.warn(`⚠️  ${pc.yellow(msg)}`),
  error: (msg: string) => console.error(`❌ ${pc.red(msg)}`),
  header: (msg: string) => console.log(`\n🏢 ${pc.bold(pc.cyan(msg))}`),
};

/** Graceful process killer with fallback */
async function killProcess(proc: ChildProcess, timeoutMs = 5000): Promise<void> {
  if (!proc.pid) return;

  return new Promise((resolve) => {
    const timer = setTimeout(() => {
      log.warn(`Process ${proc.pid} didn't exit, forcing...`);
      if (process.platform === "win32") {
        spawn("taskkill", ["/F", "/T", "/PID", proc.pid!.toString()]);
      } else {
        proc.kill("SIGKILL");
      }
      resolve();
    }, timeoutMs);

    if (proc.pid) {
      // Windows often needs /T /F to kill the whole tree (node -> bun -> process)
      spawn("taskkill", ["/T", "/F", "/PID", proc.pid.toString()]);
    } else {
      proc.kill("SIGTERM");
    }

    proc.on("exit", () => {
      clearTimeout(timer);
      resolve();
    });
  });
}

/** Defensive global cleanup */
async function globalCleanup(): Promise<void> {
  if (serverProcess) {
    log.info("Terminating production server...");
    await killProcess(serverProcess);
    serverProcess = null;
  }

  try {
    if (await fs.stat(CONFIG_BACKUP_PATH).catch(() => null)) {
      log.info("Restoring original config/private.test.ts");
      await fs.copyFile(CONFIG_BACKUP_PATH, CONFIG_PATH);
      await fs.unlink(CONFIG_BACKUP_PATH);
    } else if (!originalConfigExisted && (await fs.stat(CONFIG_PATH).catch(() => null))) {
      log.info("Removing temporary benchmark config");
      await fs.unlink(CONFIG_PATH);
    }
  } catch {
    log.warn("Cleanup encountered minor issues");
  }
}

process.on("SIGINT", async () => {
  log.warn("Audit cancelled by user (SIGINT)");
  await globalCleanup();
  process.exit(1);
});

/** Prepare production config with proper typing */
async function prepareProductionConfig(dbType: string, useRedis: boolean): Promise<void> {
  const db = DATABASES.find((d) => d.type === dbType)!;
  const dbName = dbType === "sqlite" ? "sveltycms_test_matrix.db" : "SveltyCMS_test";

  const privateEnv = {
    DB_TYPE: dbType,
    DB_NAME: dbName,
    DB_HOST: db.host,
    DB_PORT: db.port?.toString() || "",
    DB_USER: "",
    DB_PASSWORD: "",
    USE_REDIS: useRedis,
    REDIS_HOST: "127.0.0.1",
    REDIS_PORT: 6379,
    JWT_SECRET_KEY: "bench-jwt-secret-key-12345",
    ENCRYPTION_KEY: "bench-encryption-key-12345",
    TEST_API_SECRET,
    MULTI_TENANT: false,
    DB_RETRY_ATTEMPTS: 2,
    DB_RETRY_DELAY: 1000,
  };

  const content = `/** 
  * Generated by Enterprise Matrix - DO NOT EDIT MANUALLY
  */
  export const privateEnv = ${JSON.stringify(privateEnv, null, 2)};
  `;
  await fs.writeFile(CONFIG_PATH, content);
}

/** Wait for server to be healthy with better polling + timeout */
async function waitForServerReady(port: number, timeoutMs = 45000): Promise<number> {
  const start = Date.now();
  const maxAttempts = Math.ceil(timeoutMs / 1000);

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const res = await fetch(`http://127.0.0.1:${port}/api/system/health`, {
        signal: AbortSignal.timeout(1000),
      });

      if (res.status < 500) {
        return Date.now() - start;
      }
    } catch {
      // ignore connection refused / timeout
    }

    if (Date.now() - start > timeoutMs) {
      throw new Error(`Server readiness timeout after ${timeoutMs}ms`);
    }

    await new Promise((r) => setTimeout(r, 1500));
  }

  throw new Error("Server failed to become ready");
}

/** Start production server and return cold start time */
async function startServer(port: number, dbType: string, useRedis: boolean): Promise<number> {
  const db = DATABASES.find((d) => d.type === dbType)!;
  const dbName = dbType === "sqlite" ? "sveltycms_test_matrix.db" : "SveltyCMS_test";

  log.info(
    `Booting production server on port ${port} (${dbType} + ${useRedis ? "Redis" : "Memory"})`,
  );

  const env = {
    ...process.env,
    NODE_ENV: "production",
    TEST_MODE: "true",
    PORT: port.toString(),
    DB_TYPE: dbType,
    DB_NAME: dbName,
    DB_HOST: db.host,
    DB_PORT: db.port?.toString() || "",
    DB_USER: "",
    DB_PASSWORD: "",
    USE_REDIS: useRedis.toString(),
    REDIS_HOST: "127.0.0.1",
    REDIS_PORT: "6379",
    TEST_API_SECRET,
    JWT_SECRET_KEY: "bench-jwt-secret-key-12345",
    ENCRYPTION_KEY: "bench-encryption-key-12345",
  };

  // Using bun for better native driver interop in production build
  serverProcess = spawn("bun", ["build/index.js"], { env, shell: true });

  // Capture logs for debugging failures
  const serverLogs: string[] = [];
  serverProcess.stdout?.on("data", (data) => {
    const msg = data.toString().trim();
    if (msg) serverLogs.push(msg);
  });
  serverProcess.stderr?.on("data", (data) => {
    const msg = data.toString().trim();
    if (msg) serverLogs.push(`${pc.red("[STDERR]")} ${msg}`);
  });

  try {
    const coldStartMs = await waitForServerReady(port);
    log.success(`Server ready in ${coldStartMs}ms`);
    return coldStartMs;
  } catch (err: any) {
    console.error(
      `\n${pc.bold(pc.redBright(" [CRASH/LOGS] "))} Last 15 lines:\n${serverLogs.slice(-15).join("\n")}`,
    );
    throw err;
  }
}

/** Clean results directory */
async function resetResultsDir(): Promise<void> {
  await fs.rm(RESULTS_DIR, { recursive: true, force: true });
  await fs.mkdir(RESULTS_DIR, { recursive: true });
}

/** Drop databases for a fresh start */
async function dropDatabases() {
  log.info("Dropping existing test databases for fresh start...");

  // SQLite
  try {
    const sqlitePath = path.join(process.cwd(), "config/database/sveltycms_test_matrix.db");
    if (await fs.stat(sqlitePath).catch(() => null)) {
      await fs.unlink(sqlitePath);
      log.info("Dropped SQLite database file.");
    }
  } catch {}

  // MongoDB
  try {
    await runCommand("docker", [
      "exec",
      "mongodb",
      "mongosh",
      "--eval",
      "db.getSiblingDB('SveltyCMS_test').dropDatabase()",
    ]);
    log.info("Dropped MongoDB database.");
  } catch {}

  // PostgreSQL
  try {
    await runCommand("docker", [
      "exec",
      "postgres",
      "psql",
      "-U",
      "postgres",
      "-c",
      'DROP DATABASE IF EXISTS "SveltyCMS_test";',
    ]);
    log.info("Dropped PostgreSQL database.");
  } catch {}

  // MariaDB
  try {
    await runCommand("docker", [
      "exec",
      "mariadb",
      "mariadb",
      "-u",
      "root",
      "-e",
      "DROP DATABASE IF EXISTS `SveltyCMS_test`;",
    ]);
    log.info("Dropped MariaDB database.");
  } catch {}
}

async function main() {
  startTime = Date.now();
  log.header("SVELTYCMS ENTERPRISE PERFORMANCE AUDIT (Zero-Mock - Enhanced)");
  console.log("=".repeat(70));

  // Backup original config
  if (await fs.stat(CONFIG_PATH).catch(() => null)) {
    originalConfigExisted = true;
    log.info("Backing up original config/private.test.ts");
    await fs.copyFile(CONFIG_PATH, CONFIG_BACKUP_PATH);
  }

  try {
    await fs.mkdir(path.join(process.cwd(), "config/database"), { recursive: true });

    // 0. Drop all test databases first
    await dropDatabases();

    // 1. Build once with stats
    log.info("[1/4] Building production binary & capturing bundle stats...");
    await fs.writeFile(
      CONFIG_PATH,
      `export const privateEnv = { DB_TYPE: 'sqlite', DB_NAME: 'build.db' };`,
    );
    await runCommand("bun", ["run", "build:stats"], { SVELTYCMS_SKIP_INIT: "true" });

    const bundleReport = JSON.parse(
      await fs.readFile(path.join(process.cwd(), "bundle-report.json"), "utf8"),
    );

    const matrixResults: BenchmarkResult[] = [];
    let passIndex = 0;

    for (const db of DATABASES) {
      for (const useRedis of [false, true]) {
        if (db.type === "sqlite" && useRedis) continue;

        const port = BASE_PORT + passIndex;
        const label = `${db.type.toUpperCase()} + ${useRedis ? "REDIS" : "MEMORY"}`;
        const dbName = db.type === "sqlite" ? "sveltycms_test_matrix.db" : "SveltyCMS_test";

        log.info(`\n🔬 Running benchmark: ${label} (Port ${port})`);
        console.log("-".repeat(60));

        try {
          await resetResultsDir();
          await prepareProductionConfig(db.type, useRedis);

          const coldStartMs = await startServer(port, db.type, useRedis);

          log.info("[2/4] Seeding enterprise data (with fresh cleanup)...");
          await runCommand("bun", ["run", "scripts/setup-system.ts", "--clean"], {
            API_BASE_URL: `http://127.0.0.1:${port}`,
            TEST_API_SECRET,
            DB_TYPE: db.type,
            DB_NAME: dbName,
            TEST_MODE: "true",
          });

          log.info("[3/4] Executing latency audit...");
          await runCommand("bun", ["test", "tests/benchmarks/rest-api-performance.test.ts"], {
            API_BASE_URL: `http://127.0.0.1:${port}`,
            TEST_MODE: "true",
            TEST_API_SECRET: TEST_API_SECRET,
          });

          // Collect metrics
          const files = await fs.readdir(RESULTS_DIR);
          const metrics: Record<string, any> = {};

          for (const file of files) {
            if (file.endsWith(".json")) {
              const data = JSON.parse(await fs.readFile(path.join(RESULTS_DIR, file), "utf8"));
              metrics[data.name] = data;
            }
          }

          matrixResults.push({
            db: db.type,
            cache: useRedis ? "Redis" : "Memory",
            status: "SUCCESS",
            coldStartMs,
            metrics,
          });

          log.success(`Pass completed: ${label}`);
        } catch (err: any) {
          log.error(`Pass failed for ${label}: ${err.message}`);
          matrixResults.push({
            db: db.type,
            cache: useRedis ? "Redis" : "Memory",
            status: "FAILED",
            error: err.message,
          });
        } finally {
          if (serverProcess) {
            await killProcess(serverProcess);
            serverProcess = null;
            await new Promise((r) => setTimeout(r, 2000)); // Graceful port drain
          }
          passIndex++;
        }
      }
    }

    await generateFinalReport(bundleReport, matrixResults);
  } catch (err: any) {
    log.error(`Audit failed: ${err.message}`);
    process.exit(1);
  } finally {
    await globalCleanup();
  }

  const totalDuration = ((Date.now() - startTime) / 1000).toFixed(1);
  log.success(`Enterprise Audit completed successfully in ${totalDuration}s`);
  process.exit(0);
}

/** Simple command runner */
async function runCommand(
  cmd: string,
  args: string[],
  env: Record<string, string> = {},
): Promise<number> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, {
      stdio: "inherit",
      shell: true,
      env: { ...process.env, ...env },
    });

    proc.on("close", (code) => {
      if (code === 0) resolve(code);
      else reject(new Error(`${cmd} ${args.join(" ")} exited with code ${code}`));
    });

    proc.on("error", reject);
  });
}

async function generateFinalReport(bundleReport: any, results: BenchmarkResult[]) {
  const { stats } = bundleReport;
  const timestamp = new Date().toLocaleString();

  let md = `## 📊 Enterprise Benchmark Matrix (April 2026 Update)\n\n`;
  md += `> [!NOTE]\n> **Last Updated**: ${timestamp} | **Strategy**: Zero-Mock Production Audit\n\n`;

  // Build stats
  md += `### 📦 Build & Footprint\n\n`;
  md += `| Metric | Production Value | Client/Server |\n`;
  md += `| :--- | :--- | :--- |\n`;
  md += `| **Build Duration** | **${(stats.buildTime / 1000).toFixed(2)}s** | N/A |\n`;
  md += `| **Module Count** | **${stats.clientModules + stats.serverModules}** | ${stats.clientModules} Client / ${stats.serverModules} Server |\n`;
  md += `| **Asset Count** | **${stats.jsCount + stats.cssCount}** | ${stats.jsCount} JS / ${stats.cssCount} CSS |\n`;
  md += `| **Brotli Size** | **${(stats.totalBrotli / 1024).toFixed(2)} KB** | Transfer-Ready |\n\n`;

  // Results matrix
  md += `### 🚀 Database & Cache Latency (p95)\n\n`;
  md += `| Engine | Cache | Cold Start | Health Check | User Context | Collections | Throughput (RPS) |\n`;
  md += `| :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n`;

  for (const res of results) {
    if (res.status === "FAILED") {
      md += `| **${res.db.toUpperCase()}** | ${res.cache} | ❌ Failed | ❌ | ❌ | ❌ | ❌ |\n`;
      continue;
    }

    const m = res.metrics || {};
    const health = m["REST: /api/system/health (Public)"]?.p95Ms?.toFixed(2) ?? "N/A";
    const userMe = m["REST: /api/user/me (Auth)"]?.p95Ms?.toFixed(2) ?? "N/A";
    const collections = m["REST: /api/collections (DB)"]?.p95Ms?.toFixed(2) ?? "N/A";
    const rps = Math.floor(m["REST: /api/collections (DB)"]?.rps ?? 0).toLocaleString();

    md += `| **${res.db.toUpperCase()}** | ${res.cache} | **${res.coldStartMs}ms** | ${health} ms | ${userMe} ms | ${collections} ms | ${rps} RPS |\n`;
  }

  // Update documentation
  let content = await fs.readFile(BENCHMARKS_DOC, "utf8").catch(() => "");
  const startMarker = "## 📊 Enterprise Benchmark Matrix";

  if (content.includes(startMarker)) {
    const before = content.slice(0, content.indexOf(startMarker));
    const afterIndex = content.indexOf("---", content.indexOf(startMarker) + startMarker.length);
    const after = afterIndex !== -1 ? content.slice(afterIndex) : "";
    content = before + md + after;
  } else {
    content = md + "\n---\n" + content;
  }

  await fs.writeFile(BENCHMARKS_DOC, content);
  log.success(`Enterprise Audit Complete. Results updated in docs/project/benchmarks.mdx`);
}

main().catch(async (err) => {
  console.error("\n💥 Fatal error in audit:", err);
  await globalCleanup();
  process.exit(1);
});
