#!/usr/bin/env bun
/**
 * @file scripts/run-integration.ts
 * @description Windows-safe integration orchestrator.
 *
 * ## Why this script exists (harness history)
 * Bun on Windows cannot reliably spawn a long-lived preview server *from inside*
 * `bun test` (Job Object / child_process quirks). Iterations that failed:
 *   1. spawn from tests/integration/harness.ts during bun test
 *   2. execSync start-and-wait inside harness
 *   3. dynamic import of node:child_process under unit preload mocks
 * Working approach (this file):
 *   **Start preview OUTSIDE bun test → then run bun test → kill preview.**
 *
 * ## Usage
 *   bun run scripts/run-integration.ts              # build + SQLite CMS + all Docker adapters
 *   bun run scripts/run-integration.ts --no-build   # reuse existing build/
 *   DB_TYPE=postgresql bun run scripts/run-integration.ts
 *
 * ## Env
 *   PORT, DB_TYPE, DB_NAME, TEST_API_SECRET, COMPILE_ALL_ADAPTERS (build)
 */

import { execSync, spawn, type ChildProcess } from "node:child_process";
import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { setTimeout as sleep } from "node:timers/promises";
import {
  getDefaultDbPort,
  getDockerDefaultDbCredentials,
  getIntegrationDbName,
} from "../src/utils/test-db-credentials.ts";

const ROOT = join(import.meta.dirname, "..");
const PORT = process.env.PORT ?? "4173";
const API_BASE_URL = process.env.API_BASE_URL ?? `http://127.0.0.1:${PORT}`;
const DB_TYPE = (process.env.DB_TYPE ?? "sqlite").toLowerCase();
const DB_NAME = process.env.DB_NAME ?? getIntegrationDbName();
const entryPoint = join(ROOT, "build", "index.js");
const NO_BUILD = process.argv.includes("--no-build");

function freePort(port: string): void {
  try {
    if (process.platform === "win32") {
      execSync(
        `powershell -NoProfile -Command "Get-NetTCPConnection -LocalPort ${port} -State Listen -ErrorAction SilentlyContinue | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue }"`,
        { stdio: "ignore" },
      );
    } else {
      execSync(`lsof -ti:${port} | xargs -r kill -9 || true`, { stdio: "ignore" });
    }
  } catch {
    /* free */
  }
}

function writePrivateTestConfig(): void {
  const creds = getDockerDefaultDbCredentials(DB_TYPE);
  const port = getDefaultDbPort(DB_TYPE);
  const configDir = join(ROOT, "config");
  if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });

  const jwt = process.env.JWT_SECRET_KEY || "Integration-Test-JWT-Secret-Key-2026-pad-to-32chars!!";
  const enc = process.env.ENCRYPTION_KEY || "Integration-Encryption-Key-2026-32ch";
  const testSecret = process.env.TEST_API_SECRET || "SVELTYCMS_TEST_SECRET_2026";

  const content = `/**
 * @file config/private.test.ts
 * @description Auto-generated by scripts/run-integration.ts — do not edit by hand.
 */
export const privateEnv = {
  DB_TYPE: ${JSON.stringify(DB_TYPE)},
  DB_HOST: ${JSON.stringify(process.env.DB_HOST || "127.0.0.1")},
  DB_PORT: ${port ? Number(port) : "undefined"},
  DB_NAME: ${JSON.stringify(DB_NAME)},
  DB_USER: ${JSON.stringify(process.env.DB_USER ?? creds.user)},
  DB_PASSWORD: ${JSON.stringify(process.env.DB_PASSWORD ?? creds.password)},
  JWT_SECRET_KEY: ${JSON.stringify(jwt)},
  ENCRYPTION_KEY: ${JSON.stringify(enc)},
  TEST_API_SECRET: ${JSON.stringify(testSecret)},
  PASSWORD_MIN_LENGTH: 8,
  USE_REDIS: false,
  MULTI_TENANT: false,
  DEMO: false,
  HOST_PROD: ${JSON.stringify(API_BASE_URL)},
};
export const privateConfig = privateEnv;
export default privateEnv;
`;
  writeFileSync(join(configDir, "private.test.ts"), content, "utf8");
  console.log(`✅ Wrote config/private.test.ts (DB_TYPE=${DB_TYPE})`);
}

function cleanSqliteFiles(): void {
  if (DB_TYPE !== "sqlite") return;
  const base = join(
    ROOT,
    "config",
    "database",
    DB_NAME.endsWith(".sqlite") ? DB_NAME : `${DB_NAME}.sqlite`,
  );
  for (const p of [
    base,
    `${base}-wal`,
    `${base}-shm`,
    join(ROOT, "config", "database", `${DB_NAME}.db`),
  ]) {
    if (existsSync(p)) {
      try {
        unlinkSync(p);
      } catch {
        /* ignore */
      }
    }
  }
}

async function waitForHealth(maxAttempts = 45): Promise<void> {
  for (let i = 0; i < maxAttempts; i++) {
    try {
      const res = await fetch(`${API_BASE_URL}/api/system/health`, {
        signal: AbortSignal.timeout(2000),
      });
      if (res.ok || res.status === 533) {
        const data = await res.json().catch(() => ({}));
        const payload = data?.data && typeof data.data === "object" ? data.data : data;
        const status = String(payload.overallStatus ?? payload.status ?? "").toLowerCase();
        if (
          [
            "ready",
            "healthy",
            "setup",
            "warmed",
            "warming",
            "degraded",
            "initializing",
            "idle",
          ].includes(status) ||
          res.ok
        ) {
          console.log(`✅ Server ready (state: ${status || res.status})`);
          return;
        }
      }
    } catch {
      /* waiting */
    }
    await sleep(1000);
  }
  throw new Error(`Server not ready at ${API_BASE_URL} after ${maxAttempts}s`);
}

function detectDockerAdapters(): string[] {
  try {
    const out =
      typeof Bun !== "undefined"
        ? new TextDecoder().decode(
            Bun.spawnSync(["docker", "ps", "--format", "{{.Names}}"], { stdout: "pipe" }).stdout,
          )
        : execSync("docker ps --format '{{.Names}}'", { encoding: "utf8" });
    const names = out.toLowerCase();
    const available = ["sqlite"]; // always
    if (names.includes("mongo")) available.push("mongodb");
    if (names.includes("postgres")) available.push("postgresql");
    if (names.includes("mariadb")) available.push("mariadb");
    return available;
  } catch {
    return ["sqlite"];
  }
}

// ── main ──────────────────────────────────────────────────────────────────

if (!NO_BUILD) {
  console.log("🏗️  Building (COMPILE_ALL_ADAPTERS=true)...");
  execSync(
    process.platform === "win32"
      ? "set COMPILE_ALL_ADAPTERS=true&& bun run build"
      : "COMPILE_ALL_ADAPTERS=true bun run build",
    { cwd: ROOT, stdio: "inherit", shell: process.platform === "win32" ? "cmd.exe" : "/bin/sh" },
  );
} else {
  console.log("ℹ️  Skipping build (--no-build)");
}

if (!existsSync(entryPoint)) {
  console.error(`❌ Missing ${entryPoint}. Run without --no-build first.`);
  process.exit(1);
}

writePrivateTestConfig();
cleanSqliteFiles();
freePort(PORT);

const dockerAdapters = detectDockerAdapters();
console.log(`🐳 Docker-available adapter suites: ${dockerAdapters.join(", ")}`);

console.log(`🚀 Starting preview on port ${PORT} (DB_TYPE=${DB_TYPE})...`);
const creds = getDockerDefaultDbCredentials(DB_TYPE);
const serverEnv: Record<string, string> = {
  ...process.env,
  PORT,
  HOST: "127.0.0.1",
  ORIGIN: API_BASE_URL,
  API_BASE_URL,
  DB_TYPE,
  DB_HOST: process.env.DB_HOST || "127.0.0.1",
  DB_PORT: process.env.DB_PORT || getDefaultDbPort(DB_TYPE),
  DB_NAME,
  DB_USER: process.env.DB_USER ?? creds.user,
  DB_PASSWORD: process.env.DB_PASSWORD ?? creds.password,
  TEST_MODE: "true",
  NODE_ENV: process.env.NODE_ENV || "test",
  JWT_SECRET_KEY:
    process.env.JWT_SECRET_KEY || "Integration-Test-JWT-Secret-Key-2026-pad-to-32chars!!",
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || "Integration-Encryption-Key-2026-32ch",
  TEST_API_SECRET: process.env.TEST_API_SECRET || "SVELTYCMS_TEST_SECRET_2026",
  PASSWORD_MIN_LENGTH: "8",
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || "Password123!",
};

const server: ChildProcess = spawn("node", [entryPoint], {
  cwd: ROOT,
  env: serverEnv,
  stdio: ["ignore", "pipe", "pipe"],
  // Windows: shell:false is required so Job Objects don't kill the preview when
  // the parent test runner exits steps; shell:true was a common failure mode.
  shell: false,
});

server.stdout?.on("data", (d) => process.stdout.write(`[srv] ${d}`));
server.stderr?.on("data", (d) => process.stderr.write(`[srv] ${d}`));
server.on("exit", (code, signal) => {
  if (code !== null && code !== 0) {
    console.error(`[srv] preview exited early code=${code} signal=${signal}`);
  }
});

let testCode = 1;
try {
  await waitForHealth();

  // Extra args after script name only (never re-pass argv[0]/[1] / this script path).
  const extraTestArgs = process.argv
    .slice(2)
    .filter((a) => a !== "--no-build" && !a.endsWith("run-integration.ts"));

  const testArgs = ["test", "--timeout", "300000", "tests/integration/", ...extraTestArgs];
  console.log(`🧪 Running: bun ${testArgs.join(" ")}`);
  console.log(`   BUN_TEST_MOCKS=false (real adapters for in-process contracts)`);

  testCode = await new Promise<number>((resolve) => {
    const tests = spawn("bun", testArgs, {
      cwd: ROOT,
      stdio: "inherit",
      shell: process.platform === "win32",
      env: {
        ...serverEnv,
        BUN_TEST_MOCKS: "false",
        // Hint for adapter suites / docs
        SVELTY_DOCKER_ADAPTERS: dockerAdapters.join(","),
      },
    });
    tests.on("close", (code) => resolve(code ?? 1));
    tests.on("error", () => resolve(1));
  });
} catch (err) {
  console.error(err instanceof Error ? err.message : err);
  testCode = 1;
} finally {
  try {
    server.kill("SIGTERM");
  } catch {
    /* ignore */
  }
  // Ensure port is free for the next run
  await sleep(500);
  freePort(PORT);
  console.log("\n🧹 Server stopped.");
}

process.exit(testCode);
