/**
 * @file scripts\secure-update.ts
 * @description Secure update script for SveltyCMS
 * 
 * This script updates dependencies and verifies the integrity of the lockfile.
 * It is recommended to run this script before committing changes to the repository.
 */

import { spawn } from 'child_process';

/**
 * Helper to run a command and stream output
 */
function runCommand(command: string, args: string[]): Promise<void> {
	return new Promise((resolve, reject) => {
		console.log(`\n> ${command} ${args.join(' ')}`);
		const child = spawn(command, args, { stdio: 'inherit', shell: true });

		child.on('close', (code) => {
			if (code === 0) {
				resolve();
			} else {
				reject(new Error(`Command failed with code ${code}`));
			}
		});
	});
}

async function main() {
	console.log('🔒 SveltyCMS Secure Update Process');
	console.log('==================================');

	try {
		// 1. Update dependencies
		console.log('\n📦 Updating dependencies...');
		await runCommand('bun', ['update']);

		// 2. Verify lockfile integrity
		console.log('\n🔐 Verifying lockfile integrity...');
		// This ensures that the lockfile generated by update is actually valid and consistent
		await runCommand('bun', ['install', '--frozen-lockfile']);

		// 3. Suggest running tests
		console.log('\n✅ Dependencies updated and lockfile verified.');
		console.log('\n⚠️  IMPORTANT: Now run the test suite to ensure no breaking changes:');
		console.log('   bun run test:all');
		
		console.log('\n🔍 It is also recommended to review the diff of bun.lockb before committing.');

	} catch (error) {
		console.error('\n❌ Update failed:', error);
		process.exit(1);
	}
}

main();
