/**
 * @file src/routes/setup/presets.ts
 * @description Defines available setup presets and starter kits for SveltyCMS.
 * Each preset now includes optional collection schemas for Quick-Start templates
 * in the Collection Builder.
 * @author SveltyCMS
 */

/**
 * A single field in a template collection.
 * Maps directly to the FieldConfig used by createWidget() in the widget factory.
 */
export interface FieldTemplate {
  /** Database field name (camelCase) */
  db_fieldName: string;
  /** Human-readable label */
  label: string;
  /** Widget type matching existing core widgets */
  type:
    | "input"
    | "richtext"
    | "image"
    | "reference"
    | "slug"
    | "number"
    | "select"
    | "repeater"
    | "seo"
    | "textarea"
    | "date"
    | "boolean"
    | "tags"
    | "file";
  /** Which widget variant to use */
  widget: string;
  /** Whether the field is required */
  required: boolean;
  /** Whether the field supports translations */
  translated: boolean;
  /** Help text shown in the CMS UI */
  helper: string;
  /** Default value */
  default?: string | number | boolean;
  /** Minimum value (for numeric fields) — prevents integer overflow at DB layer */
  min?: number;
  /** Maximum value (for numeric fields) — prevents integer overflow at DB layer */
  max?: number;
  /** Options for select/reference widgets */
  options?: string[];
}

/**
 * Represents a complete collection template within a preset.
 */
export interface CollectionPreset {
  /** Machine-readable collection name (camelCase) */
  name: string;
  /** Human-readable label */
  label: string;
  /** Iconify icon identifier */
  icon: string;
  /** Short description */
  description: string;
  /** Field definitions */
  fields: FieldTemplate[];
  /** Enable live preview for this collection */
  livePreview?: boolean | string;
  /** Plugin IDs to enable on this collection */
  plugins?: string[];
}

export interface Preset {
  complexity?: "simple" | "moderate" | "advanced";
  description: string;
  features: string[];
  icon: string;
  id: string;
  title: string;
  /** Shown in setup wizard as the recommended default path */
  recommended?: boolean;
  /** Optional collection schemas for Quick-Start templates */
  collections?: CollectionPreset[];
}

// =============================================================================
// Collection Schema Presets
// =============================================================================

/** Blog preset: Posts, Categories, Authors */
const blogCollections: CollectionPreset[] = [
  {
    name: "posts",
    label: "Posts",
    icon: "mdi:post-outline",
    description: "Blog posts with SEO support and rich text editing",
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Post title",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "content",
        label: "Content",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Post body content",
      },
      {
        db_fieldName: "excerpt",
        label: "Excerpt",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Short summary for listings",
      },
      {
        db_fieldName: "featuredImage",
        label: "Featured Image",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Hero image for the post",
      },
      {
        db_fieldName: "author",
        label: "Author",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Reference to Authors collection",
      },
      {
        db_fieldName: "categories",
        label: "Categories",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Post categories (multi-select)",
        default: undefined,
        options: ["multiple"],
      },
      {
        db_fieldName: "tags",
        label: "Tags",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Comma-separated tags",
      },
      {
        db_fieldName: "seo",
        label: "SEO",
        type: "seo",
        widget: "seo",
        required: false,
        translated: true,
        helper: "Search engine optimization metadata",
      },
    ],
  },
  {
    name: "categories",
    label: "Categories",
    icon: "mdi:tag",
    description: "Post categories for organizing content",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Category name",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Category description",
      },
    ],
  },
  {
    name: "authors",
    label: "Authors",
    icon: "mdi:account-edit",
    description: "Content authors with bios and avatars",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Author display name",
      },
      {
        db_fieldName: "bio",
        label: "Bio",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Author biography",
      },
      {
        db_fieldName: "avatar",
        label: "Avatar",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Author profile photo",
      },
      {
        db_fieldName: "email",
        label: "Email",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Public contact email",
      },
    ],
  },
];

/** Agency preset: Projects, Services, Team */
const agencyCollections: CollectionPreset[] = [
  {
    name: "projects",
    label: "Projects",
    icon: "mdi:briefcase-check",
    description: "Portfolio projects showcasing your work",
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Project title",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Project description",
      },
      {
        db_fieldName: "client",
        label: "Client",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Client name",
      },
      {
        db_fieldName: "images",
        label: "Images",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Project screenshots/gallery",
        default: undefined,
      },
      {
        db_fieldName: "testimonial",
        label: "Testimonial",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Client testimonial quote",
      },
    ],
  },
  {
    name: "services",
    label: "Services",
    icon: "mdi:cog-outline",
    description: "Services offered by your agency",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Service name",
      },
      {
        db_fieldName: "icon",
        label: "Icon",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Iconify icon name (e.g., mdi:web)",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Service description",
      },
      {
        db_fieldName: "features",
        label: "Features",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: true,
        helper: "Key features list",
      },
    ],
  },
  {
    name: "team",
    label: "Team",
    icon: "mdi:account-group",
    description: "Team members and their profiles",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Full name",
      },
      {
        db_fieldName: "role",
        label: "Role",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Job title / role",
      },
      {
        db_fieldName: "bio",
        label: "Bio",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Bio and background",
      },
      {
        db_fieldName: "photo",
        label: "Photo",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Profile photo",
      },
      {
        db_fieldName: "social",
        label: "Social Links",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Social media URLs (JSON)",
      },
    ],
  },
];

/** SaaS preset: Features, Pricing, Documentation */
const saasCollections: CollectionPreset[] = [
  {
    name: "features",
    label: "Features",
    icon: "mdi:star-outline",
    description: "Product features with descriptions and screenshots",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Feature name",
      },
      {
        db_fieldName: "icon",
        label: "Icon",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Iconify icon for the feature",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Feature description",
      },
      {
        db_fieldName: "screenshot",
        label: "Screenshot",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Feature screenshot",
      },
    ],
  },
  {
    name: "pricing",
    label: "Pricing",
    icon: "mdi:cash-multiple",
    description: "Pricing plans with features and highlighting",
    fields: [
      {
        db_fieldName: "name",
        label: "Plan Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "e.g., Starter, Pro, Enterprise",
      },
      {
        db_fieldName: "price",
        label: "Price",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Monthly price (0 for free)",
      },
      {
        db_fieldName: "features",
        label: "Features",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: true,
        helper: "Included features list",
      },
      {
        db_fieldName: "highlighted",
        label: "Highlighted",
        type: "select",
        widget: "select",
        required: false,
        translated: false,
        helper: "Whether this plan is recommended",
        default: false,
        options: ["true", "false"],
      },
    ],
  },
  {
    name: "documentation",
    label: "Documentation",
    icon: "mdi:book-open-page-variant-outline",
    description: "Product documentation articles organized by category",
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Doc page title",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "content",
        label: "Content",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Documentation content",
      },
      {
        db_fieldName: "category",
        label: "Category",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Doc category for grouping",
      },
      {
        db_fieldName: "order",
        label: "Order",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Display order within category",
      },
    ],
  },
];

/** Corporate preset: Team, Careers, Press */
const corporateCollections: CollectionPreset[] = [
  {
    name: "team",
    label: "Team",
    icon: "mdi:account-tie",
    description: "Team members across departments",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Full name",
      },
      {
        db_fieldName: "position",
        label: "Position",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Job title",
      },
      {
        db_fieldName: "bio",
        label: "Bio",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Professional biography",
      },
      {
        db_fieldName: "photo",
        label: "Photo",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Professional headshot",
      },
      {
        db_fieldName: "department",
        label: "Department",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "e.g., Engineering, Marketing",
      },
    ],
  },
  {
    name: "careers",
    label: "Careers",
    icon: "mdi:briefcase-search",
    description: "Job listings with requirements",
    fields: [
      {
        db_fieldName: "title",
        label: "Job Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Position title",
      },
      {
        db_fieldName: "department",
        label: "Department",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Department name",
      },
      {
        db_fieldName: "location",
        label: "Location",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Office location or Remote",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Full job description",
      },
      {
        db_fieldName: "requirements",
        label: "Requirements",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: true,
        helper: "List of requirements",
      },
    ],
  },
  {
    name: "press",
    label: "Press",
    icon: "mdi:newspaper-variant-outline",
    description: "Press releases and media coverage",
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Press release title",
      },
      {
        db_fieldName: "date",
        label: "Date",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Publication date",
      },
      {
        db_fieldName: "source",
        label: "Source",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Source publication name",
      },
      {
        db_fieldName: "url",
        label: "URL",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Link to original article",
      },
      {
        db_fieldName: "excerpt",
        label: "Excerpt",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Summary or excerpt",
      },
    ],
  },
];

/** E-commerce preset: Products, Categories, Orders */
const ecommerceCollections: CollectionPreset[] = [
  {
    name: "products",
    label: "Products",
    icon: "mdi:package-variant-closed",
    description: "Products with pricing, inventory, variants, and images",
    fields: [
      {
        db_fieldName: "title",
        label: "Product Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Product title",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "shortDescription",
        label: "Short Description",
        type: "textarea",
        widget: "text",
        required: false,
        translated: true,
        helper: "Brief excerpt shown in product listings and cards",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Full product description",
      },
      {
        db_fieldName: "price",
        label: "Price",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Current selling price",
      },
      {
        db_fieldName: "comparePrice",
        label: "Compare Price",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Original/compare-at price for sale display",
      },
      {
        db_fieldName: "sku",
        label: "SKU",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Stock keeping unit",
      },
      {
        db_fieldName: "stockStatus",
        label: "Stock Status",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "Current stock availability",
        default: "in_stock",
        options: ["in_stock", "out_of_stock", "on_backorder"],
      },
      {
        db_fieldName: "inventory",
        label: "Inventory Qty",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Available quantity in stock (auto-decremented on order)",
      },
      {
        db_fieldName: "lowStockThreshold",
        label: "Low Stock Threshold",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Alert when inventory drops below this number",
        default: 5,
      },
      {
        db_fieldName: "weight",
        label: "Weight",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Product weight for shipping (e.g., 0.5 kg)",
      },
      {
        db_fieldName: "dimensions",
        label: "Dimensions",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Product dimensions (e.g., 10x5x3 cm)",
      },
      {
        db_fieldName: "downloadable",
        label: "Downloadable",
        type: "input",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Is this a digital/downloadable product?",
        default: false,
      },
      {
        db_fieldName: "downloadFile",
        label: "Download File",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "File for downloadable products",
        default: undefined,
      },
      {
        db_fieldName: "tags",
        label: "Tags",
        type: "input",
        widget: "tags",
        required: false,
        translated: false,
        helper: "Product tags for filtering and search",
        default: undefined,
      },
      {
        db_fieldName: "images",
        label: "Images",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Product images/gallery",
        default: undefined,
      },
      {
        db_fieldName: "categories",
        label: "Categories",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Product categories (multi-select)",
        default: undefined,
        options: ["multiple"],
      },
      {
        db_fieldName: "variants",
        label: "Variants",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: false,
        helper: "Product variants (each with own SKU, price, inventory)",
      },
      {
        db_fieldName: "attributes",
        label: "Attributes",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: false,
        helper: "Product attributes (size, color, material, etc.)",
      },
    ],
  },
  {
    name: "product_categories",
    label: "Product Categories",
    icon: "mdi:shape-outline",
    description: "Product categories with hierarchical support",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Category name",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "image",
        label: "Image",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Category banner image",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Category description for SEO and display",
      },
      {
        db_fieldName: "parentCategory",
        label: "Parent Category",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Parent category for hierarchy",
      },
    ],
  },
  {
    name: "product_reviews",
    label: "Product Reviews",
    icon: "mdi:star-outline",
    description: "Customer ratings and reviews for products",
    fields: [
      {
        db_fieldName: "product",
        label: "Product",
        type: "reference",
        widget: "relation",
        required: true,
        translated: false,
        helper: "Reviewed product",
      },
      {
        db_fieldName: "customerEmail",
        label: "Customer Email",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Email of the reviewer",
      },
      {
        db_fieldName: "customerName",
        label: "Customer Name",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Display name of the reviewer",
      },
      {
        db_fieldName: "rating",
        label: "Rating",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Rating from 1-5 stars",
      },
      {
        db_fieldName: "review",
        label: "Review",
        type: "textarea",
        widget: "text",
        required: false,
        translated: true,
        helper: "Written review content",
      },
      {
        db_fieldName: "approved",
        label: "Approved",
        type: "input",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Review visible on storefront",
        default: false,
      },
    ],
  },
  {
    name: "coupons",
    label: "Coupons",
    icon: "mdi:ticket-percent-outline",
    description: "Discount coupons and promotional codes",
    fields: [
      {
        db_fieldName: "code",
        label: "Coupon Code",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Unique coupon code customers enter at checkout",
      },
      {
        db_fieldName: "discountType",
        label: "Discount Type",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "Type of discount",
        default: "percentage",
        options: ["percentage", "fixed_cart", "fixed_product", "free_shipping"],
      },
      {
        db_fieldName: "amount",
        label: "Amount",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Discount amount (percent or flat value)",
      },
      {
        db_fieldName: "minSpend",
        label: "Minimum Spend",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Minimum order total to use this coupon",
      },
      {
        db_fieldName: "usageLimit",
        label: "Usage Limit",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Maximum number of times this coupon can be used",
      },
      {
        db_fieldName: "expiresAt",
        label: "Expires At",
        type: "input",
        widget: "date",
        required: false,
        translated: false,
        helper: "Coupon expiration date",
      },
      {
        db_fieldName: "freeShipping",
        label: "Free Shipping",
        type: "input",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Apply free shipping with this coupon",
        default: false,
      },
    ],
  },
  {
    name: "tax_rates",
    label: "Tax Rates",
    icon: "mdi:percent-outline",
    description: "Sales tax configuration by region",
    fields: [
      {
        db_fieldName: "country",
        label: "Country",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "ISO country code (e.g., US, GB, DE)",
      },
      {
        db_fieldName: "state",
        label: "State/Region",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "State or region code (optional)",
      },
      {
        db_fieldName: "rate",
        label: "Tax Rate %",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Tax percentage (e.g., 20 for 20%)",
      },
      {
        db_fieldName: "label",
        label: "Label",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Display label (e.g., VAT, Sales Tax)",
      },
      {
        db_fieldName: "shippingTaxable",
        label: "Shipping Taxable",
        type: "input",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Apply tax to shipping costs",
        default: false,
      },
    ],
  },
  {
    name: "shipping_zones",
    label: "Shipping Zones",
    icon: "mdi:truck-delivery-outline",
    description: "Shipping zones, rates, and methods",
    fields: [
      {
        db_fieldName: "name",
        label: "Zone Name",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Zone name (e.g., Domestic, EU, Worldwide)",
      },
      {
        db_fieldName: "countries",
        label: "Countries",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Comma-separated ISO country codes",
      },
      {
        db_fieldName: "method",
        label: "Shipping Method",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "Shipping method type",
        default: "flat_rate",
        options: ["flat_rate", "free_shipping", "local_pickup"],
      },
      {
        db_fieldName: "rate",
        label: "Shipping Rate",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Flat rate shipping cost",
      },
      {
        db_fieldName: "freeThreshold",
        label: "Free Shipping Threshold",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Order total for free shipping",
      },
    ],
  },
  {
    name: "carts",
    label: "Carts",
    icon: "mdi:cart-outline",
    description: "Active shopping carts (guest and logged-in)",
    fields: [
      {
        db_fieldName: "sessionId",
        label: "Session ID",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Session or user identifier",
      },
      {
        db_fieldName: "customer",
        label: "Customer",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Reference to registered customer (null for guest)",
      },
      {
        db_fieldName: "items",
        label: "Items",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: false,
        helper: "Cart line items with product ID, qty, and price",
      },
      {
        db_fieldName: "subtotal",
        label: "Subtotal",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Calculated cart subtotal",
        default: 0,
      },
      {
        db_fieldName: "appliedCoupon",
        label: "Applied Coupon",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Coupon code applied to cart",
      },
      {
        db_fieldName: "expiresAt",
        label: "Expires At",
        type: "date",
        widget: "date",
        required: false,
        translated: false,
        helper: "Cart expiration (abandoned cart cleanup)",
      },
    ],
  },
  {
    name: "orders",
    label: "Orders",
    icon: "mdi:receipt",
    description: "Customer orders with line items, shipping, and status tracking",
    fields: [
      {
        db_fieldName: "orderNumber",
        label: "Order Number",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Unique order identifier (auto-generated)",
      },
      {
        db_fieldName: "customer",
        label: "Customer",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Reference to registered customer account",
      },
      {
        db_fieldName: "customerEmail",
        label: "Customer Email",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Customer email for guest orders and notifications",
      },
      {
        db_fieldName: "items",
        label: "Items",
        type: "repeater",
        widget: "repeater",
        required: true,
        translated: false,
        helper: "Order line items (product, qty, price)",
      },
      {
        db_fieldName: "subtotal",
        label: "Subtotal",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Subtotal before tax and shipping",
      },
      {
        db_fieldName: "shippingTotal",
        label: "Shipping Total",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Shipping cost",
        default: 0,
      },
      {
        db_fieldName: "taxTotal",
        label: "Tax Total",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Total tax amount",
        default: 0,
      },
      {
        db_fieldName: "discountTotal",
        label: "Discount Total",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Coupon/discount amount applied",
        default: 0,
      },
      {
        db_fieldName: "total",
        label: "Total",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Order grand total",
      },
      {
        db_fieldName: "status",
        label: "Status",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "Order fulfillment status",
        default: "pending",
        options: ["pending", "processing", "shipped", "delivered", "cancelled", "refunded"],
      },
      {
        db_fieldName: "paymentMethod",
        label: "Payment Method",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Payment method used (e.g., Stripe, PayPal)",
      },
      {
        db_fieldName: "couponCode",
        label: "Coupon Code",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Coupon code applied to this order",
      },
      {
        db_fieldName: "shippingAddress",
        label: "Shipping Address",
        type: "textarea",
        widget: "text",
        required: false,
        translated: false,
        helper: "Shipping address for the order",
      },
      {
        db_fieldName: "billingAddress",
        label: "Billing Address",
        type: "textarea",
        widget: "text",
        required: false,
        translated: false,
        helper: "Billing address for the order",
      },
      {
        db_fieldName: "notes",
        label: "Order Notes",
        type: "textarea",
        widget: "text",
        required: false,
        translated: false,
        helper: "Internal notes and customer order notes",
      },
      {
        db_fieldName: "shippingZone",
        label: "Shipping Zone",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Shipping zone used for rate calculation",
      },
    ],
  },
];

/** Website starter: Pages collection for the in-repo SvelteKit site template */
const websiteStarterCollections: CollectionPreset[] = [
  {
    name: "pages",
    label: "Pages",
    icon: "mdi:file-document-outline",
    description: "Frontend pages for the in-repo SvelteKit site starter with Svedit block editing",
    livePreview: "/{slug}?lang={lang}",
    plugins: ["editable-website"],
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Page title shown in browser tab and headings",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL path — use 'home' for the homepage (/)",
      },
      {
        db_fieldName: "pageType",
        label: "Page Type",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "static = fully CMS-driven; template = mixed with dynamic routes",
        default: "static",
        options: ["static", "template"],
      },
      {
        db_fieldName: "template",
        label: "Template",
        type: "select",
        widget: "select",
        required: false,
        translated: false,
        helper: "Frontend layout template key",
        default: "default",
        options: ["homepage", "default", "search", "product-detail"],
      },
      {
        db_fieldName: "heroHeading",
        label: "Hero Heading",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Large hero headline",
      },
      {
        db_fieldName: "heroSubheading",
        label: "Hero Subheading",
        type: "textarea",
        widget: "text",
        required: false,
        translated: true,
        helper: "Supporting hero text",
      },
      {
        db_fieldName: "body",
        label: "Body",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Main page content (HTML)",
      },
      {
        db_fieldName: "ctaText",
        label: "CTA Text",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Call-to-action button label",
      },
      {
        db_fieldName: "ctaHref",
        label: "CTA Link",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Call-to-action URL",
      },
      {
        db_fieldName: "content",
        label: "Page Layout (Svedit)",
        type: "textarea",
        widget: "text",
        required: false,
        translated: false,
        helper: "Primary page layout as a Svedit document JSON — edited inline in Live Preview",
      },
      {
        db_fieldName: "seo",
        label: "SEO",
        type: "seo",
        widget: "seo",
        required: false,
        translated: true,
        helper: "Search engine metadata",
      },
    ],
  },
];

// =============================================================================
// Complete Preset Definitions
// =============================================================================

export const PRESETS: Preset[] = [
  {
    id: "website",
    title: "Website Starter",
    description:
      "Recommended: SvelteKit frontend in the same repo with Svedit inline page design. Includes a seeded homepage, Pages collection, and Live Preview. Still headless-ready — swap the frontend for Astro/React later.",
    icon: "mdi:web",
    recommended: true,
    features: [
      "SvelteKit Site Starter",
      "Svedit Block Editing",
      "Seeded Homepage",
      "Live Preview Plugin",
      "Pages Collection",
    ],
    complexity: "simple",
    collections: websiteStarterCollections,
  },
  {
    id: "blank",
    title: "Blank Project",
    description: "Start from scratch with a clean slate.",
    icon: "mdi:file-outline",
    features: ["Core System", "No Collections", "Basic Settings"],
    complexity: "simple",
    collections: [],
  },
  {
    id: "blog",
    title: "Blog / Editorial",
    description:
      "Classic blog setup with posts, categories, and authors. Perfect for content creators.",
    icon: "mdi:post-outline",
    features: ["Posts Collection", "Categories", "Authors", "SEO Config", "Rich Text Editing"],
    complexity: "simple",
    collections: blogCollections,
  },
  {
    id: "agency",
    title: "Agency / Portfolio",
    description: "Showcase work, services, and client testimonials. Optimized for agencies.",
    icon: "mdi:briefcase-outline",
    features: ["Projects & Portfolio", "Services", "Clients", "Testimonials", "Media Library"],
    complexity: "moderate",
    collections: agencyCollections,
  },
  {
    id: "saas",
    title: "SaaS Product",
    description: "Documentation, features, and pricing management for modern SaaS applications.",
    icon: "mdi:cloud-outline",
    features: ["Documentation", "Pricing Plans", "Features", "Changelog", "Multi-tenant Support"],
    complexity: "moderate",
    collections: saasCollections,
  },
  {
    id: "corporate",
    title: "Corporate Site",
    description:
      "Professional presence with team, careers, and locations. Built for large organizations.",
    icon: "mdi:domain",
    features: ["Team Members", "Careers / Jobs", "Locations", "Press", "Audit Logs"],
    complexity: "moderate",
    collections: corporateCollections,
  },
  {
    id: "ecommerce",
    title: "E-commerce",
    description: "Complete online store with products, orders, and customers. Ready for scale.",
    icon: "mdi:shopping-outline",
    features: [
      "Products & Variants",
      "Orders & Customers",
      "Coupons & Discounts",
      "Product Reviews",
      "Tax Configuration",
      "Shipping Zones & Rates",
      "Inventory & Stock Alerts",
      "Stripe Payments",
      "Price & Repeater Widgets",
      "CRM Basics",
    ],
    complexity: "advanced",
    collections: ecommerceCollections,
  },
];
