/**
 * @file src/routes/setup/presets.ts
 * @description Defines available setup presets and starter kits for SveltyCMS.
 * Each preset now includes optional collection schemas for Quick-Start templates
 * in the Collection Builder.
 * @author SveltyCMS
 */

/**
 * A single field in a template collection.
 * Maps directly to the FieldConfig used by createWidget() in the widget factory.
 */
export interface FieldTemplate {
  /** Database field name (camelCase) */
  db_fieldName: string;
  /** Human-readable label */
  label: string;
  /** Widget type matching existing core widgets */
  type:
    | "input"
    | "richtext"
    | "image"
    | "reference"
    | "slug"
    | "number"
    | "select"
    | "repeater"
    | "seo"
    | "textarea"
    | "date"
    | "boolean"
    | "tags"
    | "file";
  /** Which widget variant to use */
  widget: string;
  /** Whether the field is required */
  required: boolean;
  /** Whether the field supports translations */
  translated: boolean;
  /** Help text shown in the CMS UI */
  helper: string;
  /** Default value */
  default?: string | number | boolean;
  /** Minimum value (for numeric fields) — prevents integer overflow at DB layer */
  min?: number;
  /** Maximum value (for numeric fields) — prevents integer overflow at DB layer */
  max?: number;
  /** Options for select widgets */
  options?: string[];
  /** Repeater row schema. Empty means the editor cannot store the keys checkout reads. */
  fields?: FieldTemplate[];
  /** Relation target collection `_id`. */
  collection?: string;
  /** Field shown in the relation picker. */
  displayField?: string;
  /** Relation stores an array of ids. */
  multiple?: boolean;
}

/**
 * Represents a complete collection template within a preset.
 */
export interface CollectionPreset {
  /** Machine-readable collection name (camelCase) */
  name: string;
  /** Human-readable label */
  label: string;
  /** Iconify icon identifier */
  icon: string;
  /** Short description */
  description: string;
  /** Field definitions */
  fields: FieldTemplate[];
  /** Enable live preview for this collection */
  livePreview?: boolean | string;
  /** Plugin IDs to enable on this collection */
  plugins?: string[];
  /** Display order in the generated content tree. */
  order?: number;
}

export interface Preset {
  complexity?: "simple" | "moderate" | "advanced";
  description: string;
  features: string[];
  icon: string;
  id: string;
  title: string;
  /** Shown in setup wizard as the recommended default path */
  recommended?: boolean;
  /** Optional collection schemas for Quick-Start templates */
  collections?: CollectionPreset[];
}

/** One line inside a repeater, so the editor has a key to save. */
function textItem(label: string): FieldTemplate {
  return {
    db_fieldName: "text",
    label,
    type: "input",
    widget: "text",
    required: true,
    translated: true,
    helper: label,
  };
}

function textList(name: string, label: string, helper: string, itemLabel: string): FieldTemplate {
  return {
    db_fieldName: name,
    label,
    type: "repeater",
    widget: "repeater",
    required: false,
    translated: true,
    helper,
    fields: [textItem(itemLabel)],
  };
}

// =============================================================================
// Collection Schema Presets
// =============================================================================

/** Blog preset: Posts, Categories, Authors */
const blogCollections: CollectionPreset[] = [
  {
    name: "posts",
    label: "Posts",
    icon: "mdi:post-outline",
    description: "Blog posts with SEO support and rich text editing",
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Post title",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "content",
        label: "Content",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Post body content",
      },
      {
        db_fieldName: "excerpt",
        label: "Excerpt",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Short summary for listings",
      },
      {
        db_fieldName: "featuredImage",
        label: "Featured Image",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Hero image for the post",
      },
      {
        db_fieldName: "author",
        label: "Author",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Author of this post",
        collection: "authors",
        displayField: "name",
      },
      {
        db_fieldName: "categories",
        label: "Categories",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Post categories",
        collection: "categories",
        displayField: "name",
        multiple: true,
      },
      {
        db_fieldName: "tags",
        label: "Tags",
        type: "tags",
        widget: "tags",
        required: false,
        translated: false,
        helper: "Tags for this post",
      },
      {
        db_fieldName: "seo",
        label: "SEO",
        type: "seo",
        widget: "seo",
        required: false,
        translated: true,
        helper: "Search engine optimization metadata",
      },
    ],
  },
  {
    name: "categories",
    label: "Categories",
    icon: "mdi:tag",
    description: "Post categories for organizing content",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Category name",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "parent",
        label: "Parent",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Parent category. Empty means a top-level category.",
        collection: "categories",
        displayField: "name",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Category description",
      },
    ],
  },
  {
    name: "authors",
    label: "Authors",
    icon: "mdi:account-edit",
    description: "Content authors with bios and avatars",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Author display name",
      },
      {
        db_fieldName: "bio",
        label: "Bio",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Author biography",
      },
      {
        db_fieldName: "avatar",
        label: "Avatar",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Author profile photo",
      },
      {
        db_fieldName: "email",
        label: "Email",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Public contact email",
      },
    ],
  },
];

/** Agency preset: Projects, Services, Team */
const agencyCollections: CollectionPreset[] = [
  {
    name: "projects",
    label: "Projects",
    icon: "mdi:briefcase-check",
    description: "Portfolio projects showcasing your work",
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Project title",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Project description",
      },
      {
        db_fieldName: "client",
        label: "Client",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Client name",
      },
      {
        db_fieldName: "images",
        label: "Images",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Project screenshots/gallery",
        default: undefined,
      },
      {
        db_fieldName: "testimonial",
        label: "Testimonial",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Client testimonial quote",
      },
    ],
  },
  {
    name: "services",
    label: "Services",
    icon: "mdi:cog-outline",
    description: "Services offered by your agency",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Service name",
      },
      {
        db_fieldName: "icon",
        label: "Icon",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Iconify icon name (e.g., mdi:web)",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Service description",
      },
      textList("features", "Features", "Key features of this service", "Feature"),
    ],
  },
  {
    name: "team",
    label: "Team",
    icon: "mdi:account-group",
    description: "Team members and their profiles",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Full name",
      },
      {
        db_fieldName: "role",
        label: "Role",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Job title / role",
      },
      {
        db_fieldName: "bio",
        label: "Bio",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Bio and background",
      },
      {
        db_fieldName: "photo",
        label: "Photo",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Profile photo",
      },
      {
        db_fieldName: "social",
        label: "Social Links",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: false,
        helper: "Profile links",
        fields: [
          {
            db_fieldName: "label",
            label: "Label",
            type: "input",
            widget: "text",
            required: true,
            translated: false,
            helper: "e.g. Website",
          },
          {
            db_fieldName: "url",
            label: "URL",
            type: "input",
            widget: "text",
            required: true,
            translated: false,
            helper: "https://example.com",
          },
        ],
      },
    ],
  },
];

/** SaaS preset: Features, Pricing, Documentation */
const saasCollections: CollectionPreset[] = [
  {
    name: "features",
    label: "Features",
    icon: "mdi:star-outline",
    description: "Product features with descriptions and screenshots",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Feature name",
      },
      {
        db_fieldName: "icon",
        label: "Icon",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Iconify icon for the feature",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Feature description",
      },
      {
        db_fieldName: "screenshot",
        label: "Screenshot",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Feature screenshot",
      },
    ],
  },
  {
    name: "pricing",
    label: "Pricing",
    icon: "mdi:cash-multiple",
    description: "Pricing plans with features and highlighting",
    fields: [
      {
        db_fieldName: "name",
        label: "Plan Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "e.g., Starter, Pro, Enterprise",
      },
      {
        db_fieldName: "price",
        label: "Price",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper:
          "Gross amount in major units (19.00). 0 is a free plan. A consumer price in the EU usually includes VAT.",
      },
      {
        db_fieldName: "currency",
        label: "Currency",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "ISO 4217 code shown next to the price",
        default: "EUR",
      },
      {
        db_fieldName: "interval",
        label: "Billing interval",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "How often this gross price applies",
        default: "month",
        options: ["month", "year", "once"],
      },
      textList("features", "Features", "What this plan includes", "Feature"),
      {
        db_fieldName: "highlighted",
        label: "Highlighted",
        type: "boolean",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Show this plan as the recommended one",
        default: false,
      },
    ],
  },
  {
    name: "documentation",
    label: "Documentation",
    icon: "mdi:book-open-page-variant-outline",
    description: "Product documentation articles organized by category",
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Doc page title",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "content",
        label: "Content",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Documentation content",
      },
      {
        db_fieldName: "category",
        label: "Category",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Doc category for grouping",
      },
      {
        db_fieldName: "order",
        label: "Order",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Display order within category",
      },
    ],
  },
];

/** Corporate preset: Team, Careers, Press */
const corporateCollections: CollectionPreset[] = [
  {
    name: "team",
    label: "Team",
    icon: "mdi:account-tie",
    description: "Team members across departments",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Full name",
      },
      {
        db_fieldName: "position",
        label: "Position",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Job title",
      },
      {
        db_fieldName: "bio",
        label: "Bio",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Professional biography",
      },
      {
        db_fieldName: "photo",
        label: "Photo",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Professional headshot",
      },
      {
        db_fieldName: "department",
        label: "Department",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "e.g., Engineering, Marketing",
      },
    ],
  },
  {
    name: "careers",
    label: "Careers",
    icon: "mdi:briefcase-search",
    description: "Job listings with requirements",
    fields: [
      {
        db_fieldName: "title",
        label: "Job Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Position title",
      },
      {
        db_fieldName: "department",
        label: "Department",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Department name",
      },
      {
        db_fieldName: "location",
        label: "Location",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Office location or Remote",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Full job description",
      },
      textList("requirements", "Requirements", "What the applicant should bring", "Requirement"),
    ],
  },
  {
    name: "press",
    label: "Press",
    icon: "mdi:newspaper-variant-outline",
    description: "Press releases and media coverage",
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Press release title",
      },
      {
        db_fieldName: "date",
        label: "Date",
        type: "date",
        widget: "date",
        required: true,
        translated: false,
        helper: "Publication date",
      },
      {
        db_fieldName: "source",
        label: "Source",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Source publication name",
      },
      {
        db_fieldName: "url",
        label: "URL",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Link to original article",
      },
      {
        db_fieldName: "excerpt",
        label: "Excerpt",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Summary or excerpt",
      },
    ],
  },
];

/** E-commerce preset: Products, Categories, Orders */
/** Variant row. Checkout reads sku, price, and inventory by these names. */
const productVariantFields: FieldTemplate[] = [
  {
    db_fieldName: "sku",
    label: "SKU",
    type: "input",
    widget: "text",
    required: true,
    translated: false,
    helper: "Variant SKU. Checkout matches the line to this value.",
  },
  {
    db_fieldName: "title",
    label: "Title",
    type: "input",
    widget: "text",
    required: false,
    translated: true,
    helper: "Variant label, such as Small or Blue",
  },
  {
    db_fieldName: "price",
    label: "Price",
    type: "number",
    widget: "number",
    required: false,
    translated: false,
    helper: "Variant price in major units (19.99). Blank uses the product price.",
  },
  {
    db_fieldName: "inventory",
    label: "Inventory Qty",
    type: "number",
    widget: "number",
    required: false,
    translated: false,
    helper: "Quantity for this variant. Decremented when an order is placed.",
  },
  {
    db_fieldName: "downloadable",
    label: "Downloadable",
    type: "boolean",
    widget: "checkbox",
    required: false,
    translated: false,
    helper: "This variant is a digital file",
    default: false,
  },
];

/** Cart and order lines. Names match the objects checkout writes. */
const commerceLineFields: FieldTemplate[] = [
  {
    db_fieldName: "productId",
    label: "Product ID",
    type: "input",
    widget: "text",
    required: true,
    translated: false,
    helper: "Product entry id",
  },
  {
    db_fieldName: "variantSku",
    label: "Variant SKU",
    type: "input",
    widget: "text",
    required: false,
    translated: false,
    helper: "Variant SKU when the line is not the base product",
  },
  {
    db_fieldName: "title",
    label: "Title",
    type: "input",
    widget: "text",
    required: false,
    translated: false,
    helper: "Line title captured at checkout",
  },
  {
    db_fieldName: "sku",
    label: "SKU",
    type: "input",
    widget: "text",
    required: false,
    translated: false,
    helper: "SKU captured at checkout",
  },
  {
    db_fieldName: "qty",
    label: "Quantity",
    type: "number",
    widget: "number",
    required: true,
    translated: false,
    helper: "Quantity",
  },
  {
    db_fieldName: "unitAmount",
    label: "Unit Amount (cents)",
    type: "number",
    widget: "number",
    required: false,
    translated: false,
    helper: "Unit price in minor units",
  },
  {
    db_fieldName: "currency",
    label: "Currency",
    type: "input",
    widget: "text",
    required: false,
    translated: false,
    helper: "ISO 4217 currency code",
  },
  {
    db_fieldName: "downloadable",
    label: "Downloadable",
    type: "boolean",
    widget: "checkbox",
    required: false,
    translated: false,
    helper: "Digital line",
    default: false,
  },
  {
    db_fieldName: "taxClass",
    label: "VAT class",
    type: "select",
    widget: "select",
    required: false,
    translated: false,
    helper: "standard, reduced, or zero. Captured when the line is added.",
    default: "standard",
    options: ["standard", "reduced", "zero"],
  },
];

const ecommerceCollections: CollectionPreset[] = [
  {
    name: "products",
    label: "Products",
    icon: "mdi:package-variant-closed",
    description: "Products with pricing, inventory, variants, and images",
    fields: [
      {
        db_fieldName: "title",
        label: "Product Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Product title",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "shortDescription",
        label: "Short Description",
        type: "textarea",
        widget: "text",
        required: false,
        translated: true,
        helper: "Brief excerpt shown in product listings and cards",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: true,
        translated: true,
        helper: "Full product description",
      },
      {
        db_fieldName: "price",
        label: "Price",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Gross price in major units, including VAT (19.99).",
      },
      {
        db_fieldName: "taxClass",
        label: "VAT class",
        type: "select",
        widget: "select",
        required: false,
        translated: false,
        helper: "standard uses the country rate. reduced uses reducedRate. zero is 0%.",
        default: "standard",
        options: ["standard", "reduced", "zero"],
      },
      {
        db_fieldName: "comparePrice",
        label: "Compare Price",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Earlier shelf price. A reduction is announced only with the 30-day low.",
      },
      {
        db_fieldName: "priceHistory",
        label: "Price history",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: false,
        helper: "Previous gross prices. Written when the price changes.",
        fields: [
          {
            db_fieldName: "amount",
            label: "Amount",
            type: "number",
            widget: "number",
            required: true,
            translated: false,
            helper: "Gross price before the change",
          },
          {
            db_fieldName: "recordedAt",
            label: "Recorded at",
            type: "date",
            widget: "date",
            required: true,
            translated: false,
            helper: "When this price was still current",
          },
        ],
      },
      {
        db_fieldName: "sku",
        label: "SKU",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Stock keeping unit",
      },
      {
        db_fieldName: "inventory",
        label: "Inventory Qty",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Available quantity in stock (auto-decremented on order)",
      },
      {
        db_fieldName: "lowStockThreshold",
        label: "Low Stock Threshold",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Alert when inventory drops below this number",
        default: 5,
      },
      {
        db_fieldName: "weight",
        label: "Weight",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Product weight for shipping (e.g., 0.5 kg)",
      },
      {
        db_fieldName: "dimensions",
        label: "Dimensions",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Product dimensions (e.g., 10x5x3 cm)",
      },
      {
        db_fieldName: "downloadable",
        label: "Downloadable",
        type: "boolean",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Is this a digital/downloadable product?",
        default: false,
      },
      {
        db_fieldName: "downloadFile",
        label: "Download File",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "File for downloadable products",
      },
      {
        db_fieldName: "tags",
        label: "Tags",
        type: "input",
        widget: "tags",
        required: false,
        translated: false,
        helper: "Product tags for filtering and search",
      },
      {
        db_fieldName: "images",
        label: "Images",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Product images/gallery",
      },
      {
        db_fieldName: "categories",
        label: "Categories",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Product categories",
        collection: "product_categories",
        displayField: "name",
        multiple: true,
      },
      {
        db_fieldName: "variants",
        label: "Variants",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: false,
        helper: "Each variant has its own SKU, price, and inventory",
        fields: productVariantFields,
      },
      {
        db_fieldName: "attributes",
        label: "Attributes",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: false,
        helper: "Display attributes such as size or color. Checkout uses variants.",
        fields: [
          {
            db_fieldName: "name",
            label: "Name",
            type: "input",
            widget: "text",
            required: true,
            translated: false,
            helper: "Attribute name, such as Size",
          },
          {
            db_fieldName: "value",
            label: "Value",
            type: "input",
            widget: "text",
            required: true,
            translated: true,
            helper: "Attribute value, such as Medium",
          },
        ],
      },
    ],
  },
  {
    name: "product_categories",
    label: "Product Categories",
    icon: "mdi:shape-outline",
    description: "Product categories with hierarchical support",
    fields: [
      {
        db_fieldName: "name",
        label: "Name",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Category name",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL-friendly identifier",
      },
      {
        db_fieldName: "image",
        label: "Image",
        type: "image",
        widget: "media-upload",
        required: false,
        translated: false,
        helper: "Category banner image",
      },
      {
        db_fieldName: "description",
        label: "Description",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Category description for SEO and display",
      },
      {
        db_fieldName: "parentCategory",
        label: "Parent Category",
        type: "reference",
        widget: "relation",
        required: false,
        translated: false,
        helper: "Parent category for hierarchy",
        collection: "product_categories",
        displayField: "name",
      },
    ],
  },
  {
    name: "product_reviews",
    label: "Product Reviews",
    icon: "mdi:star-outline",
    description: "Customer ratings and reviews for products",
    fields: [
      {
        db_fieldName: "product",
        label: "Product",
        type: "reference",
        widget: "relation",
        required: true,
        translated: false,
        helper: "Reviewed product",
        collection: "products",
        displayField: "title",
      },
      {
        db_fieldName: "customerEmail",
        label: "Customer Email",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Email of the reviewer",
      },
      {
        db_fieldName: "customerName",
        label: "Customer Name",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Display name of the reviewer",
      },
      {
        db_fieldName: "rating",
        label: "Rating",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Rating from 1-5 stars",
      },
      {
        db_fieldName: "review",
        label: "Review",
        type: "textarea",
        widget: "text",
        required: false,
        translated: true,
        helper: "Written review content",
      },
      {
        db_fieldName: "approved",
        label: "Approved",
        type: "boolean",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Review visible on storefront",
        default: false,
      },
    ],
  },
  {
    name: "coupons",
    label: "Coupons",
    icon: "mdi:ticket-percent-outline",
    description: "Discount coupons and promotional codes",
    fields: [
      {
        db_fieldName: "code",
        label: "Coupon Code",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Unique coupon code customers enter at checkout",
      },
      {
        db_fieldName: "discountType",
        label: "Discount Type",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "Type of discount",
        default: "percentage",
        options: ["percentage", "fixed_cart", "fixed_product", "free_shipping"],
      },
      {
        db_fieldName: "amount",
        label: "Amount",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Discount amount (percent or flat value)",
      },
      {
        db_fieldName: "minSpend",
        label: "Minimum Spend",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Minimum order total to use this coupon",
      },
      {
        db_fieldName: "usageLimit",
        label: "Usage Limit",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Maximum number of times this coupon can be used",
      },
      {
        db_fieldName: "usedCount",
        label: "Used Count",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Auto-incremented on order placement (server-managed)",
        default: 0,
      },
      {
        db_fieldName: "expiresAt",
        label: "Expires At",
        type: "date",
        widget: "date",
        required: false,
        translated: false,
        helper: "Coupon expiration date",
      },
      {
        db_fieldName: "freeShipping",
        label: "Free Shipping",
        type: "boolean",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Apply free shipping with this coupon",
        default: false,
      },
    ],
  },
  {
    name: "tax_rates",
    label: "Tax Rates",
    icon: "mdi:percent-outline",
    description: "Sales tax configuration by region",
    fields: [
      {
        db_fieldName: "country",
        label: "Country",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "ISO country code (e.g., US, GB, DE)",
      },
      {
        db_fieldName: "state",
        label: "State/Region",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "State or region code (optional)",
      },
      {
        db_fieldName: "rate",
        label: "Tax Rate %",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Tax percentage (e.g., 20 for 20%)",
      },
      {
        db_fieldName: "label",
        label: "Label",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Display label (e.g., VAT, Sales Tax)",
      },
      {
        db_fieldName: "shippingTaxable",
        label: "Shipping Taxable",
        type: "boolean",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Shipping price includes VAT at the goods rate. Off: shipping has no VAT.",
        default: true,
      },
      {
        db_fieldName: "reducedRate",
        label: "Reduced rate %",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Reduced VAT, for example 7. Blank uses the standard rate.",
      },
    ],
  },
  {
    name: "shipping_zones",
    label: "Shipping Zones",
    icon: "mdi:truck-delivery-outline",
    description: "Shipping zones, rates, and methods",
    fields: [
      {
        db_fieldName: "name",
        label: "Zone Name",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Zone name (e.g., Domestic, EU, Worldwide)",
      },
      {
        db_fieldName: "countries",
        label: "Countries",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Comma-separated ISO country codes",
      },
      {
        db_fieldName: "method",
        label: "Shipping Method",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "Shipping method type",
        default: "flat_rate",
        options: ["flat_rate", "free_shipping", "local_pickup"],
      },
      {
        db_fieldName: "rate",
        label: "Shipping Rate",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Flat rate shipping cost",
      },
      {
        db_fieldName: "freeThreshold",
        label: "Free Shipping Threshold",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Order total for free shipping",
      },
    ],
  },
  {
    name: "carts",
    label: "Carts",
    icon: "mdi:cart-outline",
    description: "Active shopping carts (guest and logged-in)",
    fields: [
      {
        db_fieldName: "sessionId",
        label: "Session ID",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Session or user identifier",
      },
      {
        db_fieldName: "customer",
        label: "Customer",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Signed-in user id. Empty for a guest cart.",
      },
      {
        db_fieldName: "items",
        label: "Items",
        type: "repeater",
        widget: "repeater",
        required: false,
        translated: false,
        helper: "Cart lines written by checkout",
        fields: commerceLineFields,
      },
      {
        db_fieldName: "subtotal",
        label: "Subtotal",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Calculated cart subtotal",
        default: 0,
      },
      {
        db_fieldName: "appliedCoupon",
        label: "Applied Coupon",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Coupon code applied to cart",
      },
      {
        db_fieldName: "expiresAt",
        label: "Expires At",
        type: "date",
        widget: "date",
        required: false,
        translated: false,
        helper: "Cart expiration (abandoned cart cleanup)",
      },
    ],
  },
  {
    name: "orders",
    label: "Orders",
    icon: "mdi:receipt",
    description: "Customer orders with line items, shipping, and status tracking",
    fields: [
      {
        db_fieldName: "orderNumber",
        label: "Order Number",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Unique order identifier (auto-generated)",
      },
      {
        db_fieldName: "customer",
        label: "Customer",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Signed-in user id. Empty for a guest order.",
      },
      {
        db_fieldName: "customerEmail",
        label: "Customer Email",
        type: "input",
        widget: "text",
        required: true,
        translated: false,
        helper: "Customer email for guest orders and notifications",
      },
      {
        db_fieldName: "items",
        label: "Items",
        type: "repeater",
        widget: "repeater",
        required: true,
        translated: false,
        helper: "Order lines captured at checkout",
        fields: commerceLineFields,
      },
      {
        db_fieldName: "subtotal",
        label: "Subtotal",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Subtotal before tax and shipping",
      },
      {
        db_fieldName: "shippingTotal",
        label: "Shipping Total",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Shipping cost",
        default: 0,
      },
      {
        db_fieldName: "taxTotal",
        label: "Tax Total",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Total tax amount",
        default: 0,
      },
      {
        db_fieldName: "discountTotal",
        label: "Discount Total",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Coupon/discount amount applied",
        default: 0,
      },
      {
        db_fieldName: "total",
        label: "Total",
        type: "number",
        widget: "number",
        required: true,
        translated: false,
        helper: "Order grand total",
      },
      {
        db_fieldName: "totalCents",
        label: "Total (cents)",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Server-computed grand total in minor units (e.g., 1999 = €19.99)",
      },
      {
        db_fieldName: "currency",
        label: "Currency",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "ISO 4217 currency code (server-set, e.g., EUR)",
      },
      {
        db_fieldName: "invoiceNumber",
        label: "Invoice number",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Server-set VAT invoice number",
      },
      {
        db_fieldName: "netTotal",
        label: "Net total",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Total excluding VAT",
      },
      {
        db_fieldName: "taxRate",
        label: "VAT rate %",
        type: "number",
        widget: "number",
        required: false,
        translated: false,
        helper: "Primary VAT rate on this order",
      },
      {
        db_fieldName: "customerName",
        label: "Customer name",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Name on the invoice",
      },
      {
        db_fieldName: "vatId",
        label: "Customer VAT ID",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "EU VAT ID when the buyer supplied one",
      },
      {
        db_fieldName: "vatNote",
        label: "VAT note",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Reverse charge or VIES note",
      },
      {
        db_fieldName: "shipLine1",
        label: "Street",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Shipping street",
      },
      {
        db_fieldName: "shipPostal",
        label: "Postal code",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Shipping postal code",
      },
      {
        db_fieldName: "shipCity",
        label: "City",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Shipping city",
      },
      {
        db_fieldName: "shipCountry",
        label: "Ship country",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "ISO country code",
      },
      {
        db_fieldName: "deliveredAt",
        label: "Delivered at",
        type: "date",
        widget: "date",
        required: false,
        translated: false,
        helper: "When the order was marked delivered. Starts the 14-day withdrawal period.",
      },
      {
        db_fieldName: "withdrawalAt",
        label: "Withdrawal at",
        type: "date",
        widget: "date",
        required: false,
        translated: false,
        helper: "When the consumer confirmed withdrawal",
      },
      {
        db_fieldName: "withdrawalName",
        label: "Withdrawal name",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Name used on the withdrawal",
      },
      {
        db_fieldName: "status",
        label: "Status",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "Order fulfillment status",
        default: "pending",
        options: ["pending", "processing", "shipped", "delivered", "cancelled", "refunded"],
      },
      {
        db_fieldName: "paymentMethod",
        label: "Payment Method",
        type: "select",
        widget: "select",
        required: false,
        translated: false,
        helper: "How the customer pays",
        default: "stripe",
        options: ["stripe", "cod", "bank_transfer"],
      },
      {
        db_fieldName: "stripePaymentIntentId",
        label: "Stripe PaymentIntent",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Server-set PaymentIntent id. Confirm rejects a mismatched intent.",
      },
      {
        db_fieldName: "trackingUrl",
        label: "Tracking URL",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "https tracking link written when the order is marked shipped",
      },
      {
        db_fieldName: "inventoryCommitted",
        label: "Inventory Committed",
        type: "boolean",
        widget: "checkbox",
        required: false,
        translated: false,
        helper: "Server flag: stock has been reserved for this order",
        default: false,
      },
      {
        db_fieldName: "couponCode",
        label: "Coupon Code",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Coupon code applied to this order",
      },
      {
        db_fieldName: "cartId",
        label: "Cart Reference",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Source cart reference (server-set)",
      },
      {
        db_fieldName: "shippingAddress",
        label: "Shipping Address",
        type: "textarea",
        widget: "text",
        required: false,
        translated: false,
        helper: "Shipping address for the order",
      },
      {
        db_fieldName: "billingAddress",
        label: "Billing Address",
        type: "textarea",
        widget: "text",
        required: false,
        translated: false,
        helper: "Billing address for the order",
      },
      {
        db_fieldName: "notes",
        label: "Order Notes",
        type: "textarea",
        widget: "text",
        required: false,
        translated: false,
        helper: "Internal notes and customer order notes",
      },
    ],
  },
];

/** Website starter: Pages collection for the in-repo SvelteKit site template */
const websiteStarterCollections: CollectionPreset[] = [
  {
    name: "pages",
    label: "Pages",
    icon: "mdi:file-document-outline",
    description: "Frontend pages for the in-repo SvelteKit site starter with Svedit block editing",
    livePreview: "/{slug}?lang={lang}",
    plugins: ["editable-website"],
    fields: [
      {
        db_fieldName: "title",
        label: "Title",
        type: "input",
        widget: "text",
        required: true,
        translated: true,
        helper: "Page title shown in browser tab and headings",
      },
      {
        db_fieldName: "slug",
        label: "Slug",
        type: "slug",
        widget: "slug",
        required: true,
        translated: false,
        helper: "URL path — use 'home' for the homepage (/)",
      },
      {
        db_fieldName: "pageType",
        label: "Page Type",
        type: "select",
        widget: "select",
        required: true,
        translated: false,
        helper: "static = fully CMS-driven; template = mixed with dynamic routes",
        default: "static",
        options: ["static", "template"],
      },
      {
        db_fieldName: "template",
        label: "Template",
        type: "select",
        widget: "select",
        required: false,
        translated: false,
        helper: "Frontend layout template key",
        default: "default",
        options: ["homepage", "default", "search", "product-detail"],
      },
      {
        db_fieldName: "heroHeading",
        label: "Hero Heading",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Large hero headline",
      },
      {
        db_fieldName: "heroSubheading",
        label: "Hero Subheading",
        type: "textarea",
        widget: "text",
        required: false,
        translated: true,
        helper: "Supporting hero text",
      },
      {
        db_fieldName: "body",
        label: "Body",
        type: "richtext",
        widget: "richtext",
        required: false,
        translated: true,
        helper: "Main page content (HTML)",
      },
      {
        db_fieldName: "ctaText",
        label: "CTA Text",
        type: "input",
        widget: "text",
        required: false,
        translated: true,
        helper: "Call-to-action button label",
      },
      {
        db_fieldName: "ctaHref",
        label: "CTA Link",
        type: "input",
        widget: "text",
        required: false,
        translated: false,
        helper: "Call-to-action URL",
      },
      {
        db_fieldName: "content",
        label: "Page Layout (Svedit)",
        type: "textarea",
        widget: "text",
        required: false,
        translated: false,
        helper: "Primary page layout as a Svedit document JSON — edited inline in Live Preview",
      },
      {
        db_fieldName: "seo",
        label: "SEO",
        type: "seo",
        widget: "seo",
        required: false,
        translated: true,
        helper: "Search engine metadata",
      },
    ],
  },
];

// =============================================================================
// Complete Preset Definitions
// =============================================================================

export const PRESETS: Preset[] = [
  {
    id: "blank",
    title: "Blank Project",
    description: "Start from scratch with a clean slate.",
    icon: "mdi:file-outline",
    features: ["Core System", "No Collections", "Basic Settings"],
    complexity: "simple",
    collections: [],
  },
  {
    id: "website",
    title: "Website Starter",
    description:
      "Recommended: SvelteKit frontend in the same repo with Svedit inline page design. Includes a seeded homepage, Pages collection, and Live Preview. Still headless-ready — swap the frontend for Astro/React later.",
    icon: "mdi:web",
    recommended: true,
    features: [
      "SvelteKit Site Starter",
      "Svedit Block Editing",
      "Seeded Homepage",
      "Live Preview Plugin",
      "Pages Collection",
      "Legal and privacy pages",
    ],
    complexity: "simple",
    collections: websiteStarterCollections,
  },
  {
    id: "blog",
    title: "Blog / Editorial",
    description:
      "Classic blog setup with posts, categories, and authors. Perfect for content creators.",
    icon: "mdi:post-outline",
    features: ["Posts", "Nested categories", "Authors", "Tags"],
    complexity: "simple",
    collections: blogCollections,
  },
  {
    id: "agency",
    title: "Agency / Portfolio",
    description: "Showcase work, services, and client testimonials. Optimized for agencies.",
    icon: "mdi:briefcase-outline",
    features: ["Projects", "Services", "Team"],
    complexity: "moderate",
    collections: agencyCollections,
  },
  {
    id: "saas",
    title: "SaaS Product",
    description: "Documentation, features, and pricing management for modern SaaS applications.",
    icon: "mdi:cloud-outline",
    features: ["Features", "Pricing plans", "Documentation"],
    complexity: "moderate",
    collections: saasCollections,
  },
  {
    id: "corporate",
    title: "Corporate Site",
    description:
      "Professional presence with team, careers, and press. Built for large organizations.",
    icon: "mdi:domain",
    features: ["Team", "Careers", "Press"],
    complexity: "moderate",
    collections: corporateCollections,
  },
  {
    id: "ecommerce",
    title: "E-commerce",
    description:
      "Catalog, carts, and orders for the Commerce plugin. Card payments stay in the Stripe plugin.",
    icon: "mdi:shopping-outline",
    features: [
      "Products & Variants",
      "Orders",
      "Coupons & Discounts",
      "Product Reviews",
      "Tax & Shipping Tables",
      "Inventory & Stock Alerts",
    ],
    complexity: "advanced",
    collections: ecommerceCollections,
  },
];
